
/* Drop Tables */

DROP TABLE MINJI.BOARD_FILE CASCADE CONSTRAINTS;
DROP TABLE MINJI.BOARD_NOTICE CASCADE CONSTRAINTS;
DROP TABLE MINJI.BOARD_OPTION CASCADE CONSTRAINTS;
DROP TABLE MINJI.BOARD_PORTFOLIO CASCADE CONSTRAINTS;
DROP TABLE MINJI.BOARD_QNA CASCADE CONSTRAINTS;
DROP TABLE MINJI.CONFIG CASCADE CONSTRAINTS;
DROP TABLE MINJI.LOGIN CASCADE CONSTRAINTS;
DROP TABLE MINJI.MEMBER CASCADE CONSTRAINTS;
DROP TABLE MINJI.MENU CASCADE CONSTRAINTS;
DROP TABLE MINJI.POPUP CASCADE CONSTRAINTS;
DROP TABLE MINJI.VISIT CASCADE CONSTRAINTS;



/* Drop Sequences */

DROP SEQUENCE MINJI.BOARD_NOTICE_SEQ;
DROP SEQUENCE MINJI.BOARD_OPTION_SEQ;
DROP SEQUENCE MINJI.BOARD_PORTFOLIO_SEQ;
DROP SEQUENCE MINJI.BOARD_QNA_SEQ;
DROP SEQUENCE MINJI.MEMBER_SEQ;
DROP SEQUENCE MINJI.MENU_SEQ;
DROP SEQUENCE MINJI.POPUP_SEQ;
DROP SEQUENCE MINJI.PRODUCT_SEQ;
DROP SEQUENCE MINJI.VISIT_SEQ;




/* Create Sequences */

CREATE SEQUENCE MINJI.BOARD_NOTICE_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999 START WITH 33 NOCACHE;
CREATE SEQUENCE MINJI.BOARD_OPTION_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999 START WITH 5 NOCACHE;
CREATE SEQUENCE MINJI.BOARD_PORTFOLIO_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999 START WITH 44 NOCACHE;
CREATE SEQUENCE MINJI.BOARD_QNA_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999 START WITH 14 NOCACHE;
CREATE SEQUENCE MINJI.MEMBER_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999 START WITH 20 NOCACHE;
CREATE SEQUENCE MINJI.MENU_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999 START WITH 19 NOCACHE;
CREATE SEQUENCE MINJI.POPUP_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999 START WITH 3 NOCACHE;
CREATE SEQUENCE MINJI.PRODUCT_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 99999 START WITH 13 NOCACHE;
CREATE SEQUENCE MINJI.VISIT_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999 START WITH 15 NOCACHE;



/* Create Tables */

CREATE TABLE MINJI.BOARD_FILE
(
	BO_TABLE varchar2(10),
	BO_IDX number(10,0),
	BF_NO number(10,0),
	BF_FILE varchar2(500),
	BF_SOURCE varchar2(500),
	BF_DOWNLOAD number(5,0),
	BF_CONTENT varchar2(500),
	BF_FILESIZE number(10,0),
	BF_DATETIME date
);


CREATE TABLE MINJI.BOARD_NOTICE
(
	BO_IDX number(10,0) NOT NULL,
	BO_WRITER varchar2(20),
	BO_MEMBER varchar2(10),
	BO_SUBJECT varchar2(200),
	BO_CONTENT varchar2(2000),
	BO_IS_SECRET number(1,0),
	BO_IS_NOTICE number(1,0),
	BO_FILE varchar2(20),
	BO_PASS varchar2(300),
	BO_REF number(10,0),
	BO_LEVEL number(10,0),
	BO_STEP number(5,0),
	BO_HIT number(10,0),
	BO_REGDATE date,
	BO_IS_VIEW number(1,0),
	BO_IP varchar2(20),
	BO_1 varchar2(200),
	BO_2 varchar2(200),
	BO_3 varchar2(200),
	BO_4 varchar2(200),
	BO_5 varchar2(200),
	CONSTRAINT SYS_C007236 PRIMARY KEY (BO_IDX)
);


CREATE TABLE MINJI.BOARD_OPTION
(
	OP_IDX number(10,0) NOT NULL UNIQUE,
	OP_NAME varchar2(20) NOT NULL,
	OP_TABLE varchar2(10) NOT NULL UNIQUE,
	OP_SKIN varchar2(20),
	OP_ADM_SKIN varchar2(20),
	OP_IS_SECRET number(1,0) DEFAULT 0,
	OP_IS_IP number(1,0) DEFAULT 0,
	OP_IS_SIGN number(1,0) DEFAULT 0,
	OP_NEW_DATE number(5,0) DEFAULT 24,
	OP_REGDATE date DEFAULT sysdate,
	OP_VIEW_LEVEL number(2,0) DEFAULT 0,
	OP_LIST_LEVEL number(2,0) DEFAULT 0,
	OP_WRITE_LEVEL number(2,0) DEFAULT 0,
	OP_COMMENT_LEVEL number(2,0) DEFAULT 0,
	OP_REPLY_LEVEL number(2,0) DEFAULT 0,
	OP_PAGE_LENGTH number(2,0) DEFAULT 10,
	OP_IS_PREVIEW number(1,0) DEFAULT 0,
	OP_IS_NOTICE number(1,0) DEFAULT 0,
	OP_CATE varchar2(1000),
	CONSTRAINT SYS_C007224 PRIMARY KEY (OP_IDX)
);


CREATE TABLE MINJI.BOARD_PORTFOLIO
(
	BO_IDX number(10,0) NOT NULL,
	BO_WRITER varchar2(20),
	BO_MEMBER varchar2(10),
	BO_SUBJECT varchar2(1000),
	BO_CONTENT varchar2(4000),
	BO_IS_SECRET number(1,0),
	BO_IS_NOTICE number(1,0),
	BO_FILE varchar2(20),
	BO_PASS varchar2(300),
	BO_REF number(10,0),
	BO_LEVEL number(10,0),
	BO_STEP number(5,0),
	BO_HIT number(10,0),
	BO_REGDATE date,
	BO_IS_VIEW number(1,0),
	BO_IP varchar2(20),
	BO_1 varchar2(200),
	BO_2 varchar2(200),
	BO_3 varchar2(200),
	BO_4 varchar2(200),
	BO_5 varchar2(200),
	CONSTRAINT SYS_C007525 PRIMARY KEY (BO_IDX)
);


CREATE TABLE MINJI.BOARD_QNA
(
	BO_IDX number(10,0) NOT NULL,
	BO_WRITER varchar2(20),
	BO_MEMBER varchar2(10),
	BO_SUBJECT varchar2(200),
	BO_CONTENT varchar2(2000),
	BO_IS_SECRET number(1,0),
	BO_IS_NOTICE number(1,0),
	BO_FILE varchar2(20),
	BO_PASS varchar2(300),
	BO_REF number(10,0),
	BO_LEVEL number(10,0),
	BO_STEP number(5,0),
	BO_HIT number(10,0),
	BO_REGDATE date,
	BO_IS_VIEW number(1,0),
	BO_IP varchar2(20),
	BO_1 varchar2(200),
	BO_2 varchar2(200),
	BO_3 varchar2(200),
	BO_4 varchar2(200),
	BO_5 varchar2(200),
	CONSTRAINT SYS_C007306 PRIMARY KEY (BO_IDX)
);


CREATE TABLE MINJI.CONFIG
(
	CF_TITLE varchar2(30),
	CF_ADMIN varchar2(20),
	CF_ADMIN_EMAIL varchar2(50),
	CF_ADMIN_NAME varchar2(20),
	CF_ADDR varchar2(50),
	CF_TEL varchar2(20),
	CF_INFO1 varchar2(100),
	CF_INFO2 varchar2(100),
	CF_INFO3 varchar2(100),
	CF_USE_ADDR number(1,0) DEFAULT 0,
	CF_USE_TEL number(1,0) DEFAULT 0,
	CF_USE_HP number(1,0) DEFAULT 0
,
	CF_PRIVACY varchar2(4000),
	CF_SERVICE varchar2(4000)
);


CREATE TABLE MINJI.LOGIN
(
	LO_IP varchar2(20),
	LO_REGDATE date,
	LO_LOCATION varchar2(500),
	LO_URL varchar2(500),
	MB_IDX number(6,0) NOT NULL
);


CREATE TABLE MINJI.MEMBER
(
	MB_IDX number(6,0) NOT NULL,
	MB_ID varchar2(20) NOT NULL,
	MB_PASS varchar2(300) NOT NULL,
	MB_NAME varchar2(20) NOT NULL,
	MB_EMAIL varchar2(30) NOT NULL,
	MB_REGDATE date DEFAULT sysdate,
	MB_LASTEST date DEFAULT sysdate,
	MB_BIRTH varchar2(10),
	MB_ZIP varchar2(10),
	MB_ADDR1 varchar2(100),
	MB_ADDR2 varchar2(100),
	MB_MAILING number(1,0) DEFAULT 0,
	MB_LEVEL number(2,0) DEFAULT 1
,
	MB_TEL varchar2(20),
	MB_HP varchar2(20),
	MB_SALT varchar2(300),
	CONSTRAINT SYS_C007194 PRIMARY KEY (MB_IDX)
);


CREATE TABLE MINJI.MENU
(
	ME_IDX number(10,0) NOT NULL,
	ME_NUM number(5,0) DEFAULT 0,
	ME_CODE varchar2(20) NOT NULL,
	ME_NAME varchar2(30) NOT NULL,
	ME_LINK varchar2(100),
	ME_IS_VIEW number(1,0) DEFAULT 0,
	ME_IS_TARGET number(1,0) DEFAULT 0,
	ME_CONTENT varchar2(1000),
	CONSTRAINT SYS_C007262 PRIMARY KEY (ME_IDX)
);


CREATE TABLE MINJI.POPUP
(
	PO_IDX number(10,0) NOT NULL,
	PO_DEVICE varchar2(10),
	PO_BEGIN_TIME date,
	PO_END_TIME date,
	PO_DISABLE_HOURS number(10,0),
	PO_LEFT number(10,0),
	PO_TOP number(10,0),
	PO_HEIGHT number(10,0),
	PO_WIDTH number(10,0),
	PO_SUBJECT varchar2(1000),
	PO_CONTENT varchar2(4000),
	CONSTRAINT SYS_C007324 PRIMARY KEY (PO_IDX)
);


CREATE TABLE MINJI.VISIT
(
	VI_IDX number(10,0) NOT NULL,
	VI_IP varchar2(20),
	VI_REGDATE date,
	VI_REFERER varchar2(200),
	VI_AGENT varchar2(100),
	VI_BROWER varchar2(100),
	VI_OS varchar2(100),
	VI_DEVICE varchar2(100),
	CONSTRAINT SYS_C007295 PRIMARY KEY (VI_IDX)
);



/* Create Foreign Keys */

ALTER TABLE MINJI.BOARD_FILE
	ADD FOREIGN KEY (BO_TABLE)
	REFERENCES MINJI.BOARD_OPTION (OP_TABLE)
;


ALTER TABLE MINJI.LOGIN
	ADD FOREIGN KEY (MB_IDX)
	REFERENCES MINJI.MEMBER (MB_IDX)
;



