INSERT INTO BOARD_OPTION (OP_IDX,
                          OP_NAME,
                          OP_TABLE,
                          OP_SKIN,
                          OP_ADM_SKIN,
                          OP_IS_SECRET,
                          OP_IS_IP,
                          OP_IS_SIGN,
                          OP_NEW_DATE,
                          OP_REGDATE,
                          OP_VIEW_LEVEL,
                          OP_LIST_LEVEL,
                          OP_WRITE_LEVEL,
                          OP_COMMENT_LEVEL,
                          OP_REPLY_LEVEL,
                          OP_PAGE_LENGTH,
                          OP_IS_PREVIEW,
                          OP_IS_NOTICE,
                          OP_CATE,
                          OP_IMG_WIDTH,
                          OP_THUMB)
     VALUES (3,
             'Q&A',
             'qna',
             'basic',
             'basic',
             1,
             1,
             1,
             24,
             TO_DATE ('03/26/2017 00:43:01', 'MM/DD/YYYY HH24:MI:SS'),
             1,
             1,
             1,
             10,
             1,
             5,
             1,
             1,
             '답변 | 질문',
             600,
             '300;300');

INSERT INTO BOARD_OPTION (OP_IDX,
                          OP_NAME,
                          OP_TABLE,
                          OP_SKIN,
                          OP_ADM_SKIN,
                          OP_IS_SECRET,
                          OP_IS_IP,
                          OP_IS_SIGN,
                          OP_NEW_DATE,
                          OP_REGDATE,
                          OP_VIEW_LEVEL,
                          OP_LIST_LEVEL,
                          OP_WRITE_LEVEL,
                          OP_COMMENT_LEVEL,
                          OP_REPLY_LEVEL,
                          OP_PAGE_LENGTH,
                          OP_IS_PREVIEW,
                          OP_IS_NOTICE,
                          OP_CATE,
                          OP_IMG_WIDTH,
                          OP_THUMB)
     VALUES (2,
             '공지사항',
             'notice',
             'basic',
             'basic',
             1,
             1,
             1,
             24,
             TO_DATE ('03/19/2017 14:10:17', 'MM/DD/YYYY HH24:MI:SS'),
             10,
             1,
             10,
             1,
             10,
             10,
             1,
             1,
             '정보|알림',
             NULL,
             NULL);

INSERT INTO BOARD_OPTION (OP_IDX,
                          OP_NAME,
                          OP_TABLE,
                          OP_SKIN,
                          OP_ADM_SKIN,
                          OP_IS_SECRET,
                          OP_IS_IP,
                          OP_IS_SIGN,
                          OP_NEW_DATE,
                          OP_REGDATE,
                          OP_VIEW_LEVEL,
                          OP_LIST_LEVEL,
                          OP_WRITE_LEVEL,
                          OP_COMMENT_LEVEL,
                          OP_REPLY_LEVEL,
                          OP_PAGE_LENGTH,
                          OP_IS_PREVIEW,
                          OP_IS_NOTICE,
                          OP_CATE,
                          OP_IMG_WIDTH,
                          OP_THUMB)
     VALUES (4,
             'Portfolio',
             'portfolio',
             'portfolio',
             'gallery',
             0,
             0,
             0,
             24,
             TO_DATE ('04/19/2017 17:57:56', 'MM/DD/YYYY HH24:MI:SS'),
             1,
             1,
             10,
             10,
             10,
             9,
             0,
             0,
             NULL,
             600,
             '405;311');

INSERT INTO CONFIG (CF_TITLE,
                    CF_ADMIN,
                    CF_ADMIN_EMAIL,
                    CF_ADMIN_NAME,
                    CF_ADDR,
                    CF_TEL,
                    CF_INFO1,
                    CF_INFO2,
                    CF_INFO3,
                    CF_USE_ADDR,
                    CF_USE_TEL,
                    CF_USE_HP,
                    CF_PRIVACY,
                    CF_SERVICE)
        VALUES (
                  '포트폴리오',
                  'admin',
                  'leeminji25@naver.com',
                  '이민지',
                  '서울시 성북구 정릉동ggg',
                  '010-2323-1211',
                  '010.3050.1240',
                  'leeminji25@naver.com',
                  'web publisher & front-end developer',
                  1,
                  0,
                  1,
                  '쉽고 편하게 이해할 수 있는 개인정보 처리방침,네이버가 먼저 시작합니다.
일반 버전
네이버(주) (이하 ''네이버'' 또는 ''회사'')는 정보통신망 이용촉진 및 정보보호 등에 관한 법률(이하, 정보통신망법), 개인정보보호법, 통신비밀보호법, 전기통신사업법 등 회사가 준수해야 할 법령상의 개인정보보호 규정을 성실히 준수하고 있습니다. 또한 OECD의 개인정보 보호 가이드라인 등 국제 기준을 준수하여 서비스를 제공합니다.

네이버는 이용자들이 회사의 개인정보 보호 정책을 보다 쉽게 이해할 수 있도록 정보통신망법에 따른 “개인정보처리방침(링크)”과는 별도로 본 “개인정보처리방침 이지버전”을 게시하고 있으며, 이는 네이버 관련 제반 서비스 (이하, 네이버 서비스)에 적용됩니다.',
                  '제 1 조 (목적)

이 약관은 네이버 주식회사 ("회사" 또는 "네이버")가 제공하는 네이버 및 네이버 관련 제반 서비스의 이용과 관련하여 회사와 회원과의 권리, 의무 및 책임사항, 기타 필요한 사항을 규정함을 목적으로 합니다.
제 2 조 (정의)

이 약관에서 사용하는 용어의 정의는 다음과 같습니다.
①"서비스"라 함은 구현되는 단말기(PC, TV, 휴대형단말기 등의 각종 유무선 장치를 포함)와 상관없이 "회원"이 이용할 수 있는 네이버 및 네이버 관련 제반 서비스를 의미합니다.
②"회원"이라 함은 회사의 "서비스"에 접속하여 이 약관에 따라 "회사"와 이용계약을 체결하고 "회사"가 제공하는 "서비스"를 이용하는 고객을 말합니다.
③"아이디(ID)"라 함은 "회원"의 식별과 "서비스" 이용을 위하여 "회원"이 정하고 "회사"가 승인하는 문자와 숫자의 조합을 의미합니다.
④"비밀번호"라 함은 "회원"이 부여 받은 "아이디와 일치되는 "회원"임을 확인하고 비밀보호를 위해 "회원" 자신이 정한 문자 또는 숫자의 조합을 의미합니다.
⑤"유료서비스"라 함은 "회사"가 유료로 제공하는 각종 온라인디지털콘텐츠(각종 정보콘텐츠, VOD, 아이템 기타 유료콘텐츠를 포함) 및 제반 서비스를 의미합니다.
⑥"포인트"라 함은 서비스의 효율적 이용을 위해 회사가 임의로 책정 또는 지급, 조정할 수 있는 재산적 가치가 없는 "서비스" 상의 가상 데이터를 의미합니다.
⑦"게시물"이라 함은 "회원"이 "서비스"를 이용함에 있어 "서비스상"에 게시한 부호ㆍ문자ㆍ음성ㆍ음향ㆍ화상ㆍ동영상 등의 정보 형태의 글, 사진, 동영상 및 각종 파일과 링크 등을 의미합니다.');

INSERT INTO POPUP (PO_IDX,
                   PO_DEVICE,
                   PO_BEGIN_TIME,
                   PO_END_TIME,
                   PO_DISABLE_HOURS,
                   PO_LEFT,
                   PO_TOP,
                   PO_HEIGHT,
                   PO_WIDTH,
                   PO_SUBJECT,
                   PO_CONTENT)
     VALUES (3,
             NULL,
             TO_DATE ('05/09/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
             TO_DATE ('06/30/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
             24,
             10,
             10,
             160,
             300,
             '메인 팝업',
             '
안녕하세요.
웹 개발자, 퍼블리셔 이민지 포트폴리오입니다.
MVC2패턴으로 JSP, Oracle, Tomcat 을 사용하여 
개발하였습니다.
'             );

INSERT INTO BOARD_QNA (BO_IDX,
                       BO_WRITER,
                       BO_MEMBER,
                       BO_SUBJECT,
                       BO_CONTENT,
                       BO_IS_SECRET,
                       BO_IS_NOTICE,
                       BO_FILE,
                       BO_PASS,
                       BO_REF,
                       BO_LEVEL,
                       BO_STEP,
                       BO_HIT,
                       BO_REGDATE,
                       BO_IS_VIEW,
                       BO_IP,
                       BO_1,
                       BO_2,
                       BO_3,
                       BO_4,
                       BO_5,
                       BO_TAG)
     VALUES (31,
             'leeminji25',
             NULL,
             '질문해주세요.',
             'Q&A 입니다.',
             0,
             0,
             '0',
             'alswl25',
             31,
             0,
             1,
             5,
             TO_DATE ('04/24/2017 06:18:08', 'MM/DD/YYYY HH24:MI:SS'),
             1,
             NULL,
             NULL,
             NULL,
             NULL,
             NULL,
             NULL,
             NULL);

INSERT INTO BOARD_QNA (BO_IDX,
                       BO_WRITER,
                       BO_MEMBER,
                       BO_SUBJECT,
                       BO_CONTENT,
                       BO_IS_SECRET,
                       BO_IS_NOTICE,
                       BO_FILE,
                       BO_PASS,
                       BO_REF,
                       BO_LEVEL,
                       BO_STEP,
                       BO_HIT,
                       BO_REGDATE,
                       BO_IS_VIEW,
                       BO_IP,
                       BO_1,
                       BO_2,
                       BO_3,
                       BO_4,
                       BO_5,
                       BO_TAG)
     VALUES (33,
             'ykish',
             NULL,
             '홈페이지가 깔끔하고 좋네요.',
             '보기 좋습니다.
홈페이지도 직접 다 만든건가요?',
             0,
             0,
             '0',
             '1234',
             33,
             0,
             1,
             2,
             TO_DATE ('05/17/2017 07:18:10', 'MM/DD/YYYY HH24:MI:SS'),
             1,
             NULL,
             NULL,
             NULL,
             NULL,
             NULL,
             NULL,
             NULL);

INSERT INTO BOARD_QNA (BO_IDX,
                       BO_WRITER,
                       BO_MEMBER,
                       BO_SUBJECT,
                       BO_CONTENT,
                       BO_IS_SECRET,
                       BO_IS_NOTICE,
                       BO_FILE,
                       BO_PASS,
                       BO_REF,
                       BO_LEVEL,
                       BO_STEP,
                       BO_HIT,
                       BO_REGDATE,
                       BO_IS_VIEW,
                       BO_IP,
                       BO_1,
                       BO_2,
                       BO_3,
                       BO_4,
                       BO_5,
                       BO_TAG)
        VALUES (
                  34,
                  '관리자',
                  'admin',
                  'RE : 홈페이지가 깔끔하고 좋네요.',
                  '안녕하세요.
네, 전부 작업하였습니다.',
                  0,
                  0,
                  '0',
                  '3fbbb66bdbfef670ab96d46cef31e49fa9298894629b9e99b65a070b8b83f169',
                  33,
                  1,
                  1,
                  1,
                  TO_DATE ('05/25/2017 13:11:04', 'MM/DD/YYYY HH24:MI:SS'),
                  1,
                  NULL,
                  NULL,
                  NULL,
                  NULL,
                  NULL,
                  NULL,
                  NULL);

INSERT INTO VISIT (VI_IDX,
                   VI_IP,
                   VI_REGDATE,
                   VI_REFERER,
                   VI_AGENT,
                   VI_BROWER,
                   VI_OS,
                   VI_DEVICE)
     VALUES (1,
             '127.0.0.1',
             TO_DATE ('03/25/2017 14:22:57', 'MM/DD/YYYY HH24:MI:SS'),
             NULL,
             NULL,
             '537.',
             '537.',
             'PC');

INSERT INTO VISIT (VI_IDX,
                   VI_IP,
                   VI_REGDATE,
                   VI_REFERER,
                   VI_AGENT,
                   VI_BROWER,
                   VI_OS,
                   VI_DEVICE)
     VALUES (2,
             '127.0.0.1',
             TO_DATE ('03/25/2017 14:25:06', 'MM/DD/YYYY HH24:MI:SS'),
             NULL,
             NULL,
             '537.',
             '537.',
             'PC');

INSERT INTO VISIT (VI_IDX,
                   VI_IP,
                   VI_REGDATE,
                   VI_REFERER,
                   VI_AGENT,
                   VI_BROWER,
                   VI_OS,
                   VI_DEVICE)
     VALUES (3,
             '127.0.0.1',
             TO_DATE ('03/25/2017 14:26:04', 'MM/DD/YYYY HH24:MI:SS'),
             NULL,
             NULL,
             '537.',
             '537.',
             'PC');

INSERT INTO VISIT (VI_IDX,
                   VI_IP,
                   VI_REGDATE,
                   VI_REFERER,
                   VI_AGENT,
                   VI_BROWER,
                   VI_OS,
                   VI_DEVICE)
     VALUES (4,
             '127.0.0.1',
             TO_DATE ('03/25/2017 14:27:18', 'MM/DD/YYYY HH24:MI:SS'),
             NULL,
             NULL,
             '537.',
             '537.',
             'PC');

INSERT INTO VISIT (VI_IDX,
                   VI_IP,
                   VI_REGDATE,
                   VI_REFERER,
                   VI_AGENT,
                   VI_BROWER,
                   VI_OS,
                   VI_DEVICE)
     VALUES (5,
             '127.0.0.1',
             TO_DATE ('03/26/2017 15:38:27', 'MM/DD/YYYY HH24:MI:SS'),
             NULL,
             NULL,
             '537.',
             '537.',
             'PC');

INSERT INTO VISIT (VI_IDX,
                   VI_IP,
                   VI_REGDATE,
                   VI_REFERER,
                   VI_AGENT,
                   VI_BROWER,
                   VI_OS,
                   VI_DEVICE)
     VALUES (6,
             '127.0.0.1',
             TO_DATE ('03/27/2017 16:44:32', 'MM/DD/YYYY HH24:MI:SS'),
             NULL,
             NULL,
             '537.',
             '537.',
             'PC');

INSERT INTO VISIT (VI_IDX,
                   VI_IP,
                   VI_REGDATE,
                   VI_REFERER,
                   VI_AGENT,
                   VI_BROWER,
                   VI_OS,
                   VI_DEVICE)
     VALUES (7,
             '127.0.0.1',
             TO_DATE ('03/28/2017 16:55:00', 'MM/DD/YYYY HH24:MI:SS'),
             NULL,
             NULL,
             '537.',
             '537.',
             'PC');

INSERT INTO VISIT (VI_IDX,
                   VI_IP,
                   VI_REGDATE,
                   VI_REFERER,
                   VI_AGENT,
                   VI_BROWER,
                   VI_OS,
                   VI_DEVICE)
     VALUES (8,
             '127.0.0.1',
             TO_DATE ('04/11/2017 11:58:27', 'MM/DD/YYYY HH24:MI:SS'),
             NULL,
             NULL,
             '537.',
             '537.',
             'PC');

INSERT INTO VISIT (VI_IDX,
                   VI_IP,
                   VI_REGDATE,
                   VI_REFERER,
                   VI_AGENT,
                   VI_BROWER,
                   VI_OS,
                   VI_DEVICE)
     VALUES (9,
             '127.0.0.1',
             TO_DATE ('04/17/2017 10:10:01', 'MM/DD/YYYY HH24:MI:SS'),
             NULL,
             NULL,
             '537.',
             '537.',
             'PC');

INSERT INTO VISIT (VI_IDX,
                   VI_IP,
                   VI_REGDATE,
                   VI_REFERER,
                   VI_AGENT,
                   VI_BROWER,
                   VI_OS,
                   VI_DEVICE)
     VALUES (10,
             '127.0.0.1',
             TO_DATE ('04/17/2017 13:05:10', 'MM/DD/YYYY HH24:MI:SS'),
             NULL,
             NULL,
             ' 7.0',
             ' 7.0',
             'PC');

INSERT INTO VISIT (VI_IDX,
                   VI_IP,
                   VI_REGDATE,
                   VI_REFERER,
                   VI_AGENT,
                   VI_BROWER,
                   VI_OS,
                   VI_DEVICE)
     VALUES (11,
             '127.0.0.1',
             TO_DATE ('04/18/2017 10:46:47', 'MM/DD/YYYY HH24:MI:SS'),
             NULL,
             NULL,
             '537.',
             '537.',
             'PC');

INSERT INTO VISIT (VI_IDX,
                   VI_IP,
                   VI_REGDATE,
                   VI_REFERER,
                   VI_AGENT,
                   VI_BROWER,
                   VI_OS,
                   VI_DEVICE)
     VALUES (12,
             '127.0.0.1',
             TO_DATE ('04/19/2017 12:42:18', 'MM/DD/YYYY HH24:MI:SS'),
             NULL,
             NULL,
             '537.',
             '537.',
             'PC');

INSERT INTO VISIT (VI_IDX,
                   VI_IP,
                   VI_REGDATE,
                   VI_REFERER,
                   VI_AGENT,
                   VI_BROWER,
                   VI_OS,
                   VI_DEVICE)
     VALUES (13,
             '127.0.0.1',
             TO_DATE ('04/19/2017 16:41:40', 'MM/DD/YYYY HH24:MI:SS'),
             NULL,
             NULL,
             '537.',
             '537.',
             'PC');

INSERT INTO VISIT (VI_IDX,
                   VI_IP,
                   VI_REGDATE,
                   VI_REFERER,
                   VI_AGENT,
                   VI_BROWER,
                   VI_OS,
                   VI_DEVICE)
     VALUES (14,
             '127.0.0.1',
             TO_DATE ('04/20/2017 18:49:31', 'MM/DD/YYYY HH24:MI:SS'),
             NULL,
             NULL,
             '537.',
             '537.',
             'PC');

INSERT INTO VISIT (VI_IDX,
                   VI_IP,
                   VI_REGDATE,
                   VI_REFERER,
                   VI_AGENT,
                   VI_BROWER,
                   VI_OS,
                   VI_DEVICE)
     VALUES (15,
             '127.0.0.1',
             TO_DATE ('04/21/2017 22:09:32', 'MM/DD/YYYY HH24:MI:SS'),
             NULL,
             NULL,
             '537.',
             '537.',
             'PC');

INSERT INTO VISIT (VI_IDX,
                   VI_IP,
                   VI_REGDATE,
                   VI_REFERER,
                   VI_AGENT,
                   VI_BROWER,
                   VI_OS,
                   VI_DEVICE)
     VALUES (16,
             '127.0.0.1',
             TO_DATE ('04/23/2017 09:36:01', 'MM/DD/YYYY HH24:MI:SS'),
             NULL,
             NULL,
             '537.',
             '537.',
             'PC');

INSERT INTO VISIT (VI_IDX,
                   VI_IP,
                   VI_REGDATE,
                   VI_REFERER,
                   VI_AGENT,
                   VI_BROWER,
                   VI_OS,
                   VI_DEVICE)
     VALUES (17,
             '121.160.41.129',
             TO_DATE ('04/25/2017 05:58:00', 'MM/DD/YYYY HH24:MI:SS'),
             NULL,
             NULL,
             '537.',
             '537.',
             'PC');

INSERT INTO VISIT (VI_IDX,
                   VI_IP,
                   VI_REGDATE,
                   VI_REFERER,
                   VI_AGENT,
                   VI_BROWER,
                   VI_OS,
                   VI_DEVICE)
     VALUES (18,
             '121.160.41.129',
             TO_DATE ('04/26/2017 06:02:00', 'MM/DD/YYYY HH24:MI:SS'),
             NULL,
             NULL,
             '537.',
             '537.',
             'PC');

INSERT INTO VISIT (VI_IDX,
                   VI_IP,
                   VI_REGDATE,
                   VI_REFERER,
                   VI_AGENT,
                   VI_BROWER,
                   VI_OS,
                   VI_DEVICE)
     VALUES (19,
             '121.160.177.76',
             TO_DATE ('05/09/2017 08:34:49', 'MM/DD/YYYY HH24:MI:SS'),
             NULL,
             NULL,
             '537.',
             '537.',
             'PC');

INSERT INTO VISIT (VI_IDX,
                   VI_IP,
                   VI_REGDATE,
                   VI_REFERER,
                   VI_AGENT,
                   VI_BROWER,
                   VI_OS,
                   VI_DEVICE)
     VALUES (20,
             '121.160.176.58',
             TO_DATE ('05/25/2017 13:18:06', 'MM/DD/YYYY HH24:MI:SS'),
             NULL,
             NULL,
             '537.',
             '537.',
             'PC');

INSERT INTO BOARD_FILE (BO_TABLE,
                        BO_IDX,
                        BF_NO,
                        BF_FILE,
                        BF_SOURCE,
                        BF_DOWNLOAD,
                        BF_CONTENT,
                        BF_FILESIZE,
                        BF_DATETIME)
        VALUES (
                  'portfolio',
                  68,
                  9,
                  'screencapture-kconbiz-cafe24-smart_office-reservation-php-1493107837707.png',
                  'screencapture-kconbiz-cafe24-smart_office-reservation-php-1493107837707.png',
                  0,
                  NULL,
                  0,
                  TO_DATE ('04/26/2017 06:06:47', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO BOARD_FILE (BO_TABLE,
                        BO_IDX,
                        BF_NO,
                        BF_FILE,
                        BF_SOURCE,
                        BF_DOWNLOAD,
                        BF_CONTENT,
                        BF_FILESIZE,
                        BF_DATETIME)
     VALUES ('portfolio',
             69,
             9,
             'scrap4.jpg',
             'scrap4.jpg',
             0,
             NULL,
             0,
             TO_DATE ('04/26/2017 06:06:25', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO BOARD_FILE (BO_TABLE,
                        BO_IDX,
                        BF_NO,
                        BF_FILE,
                        BF_SOURCE,
                        BF_DOWNLOAD,
                        BF_CONTENT,
                        BF_FILESIZE,
                        BF_DATETIME)
     VALUES ('portfolio',
             51,
             10,
             'cimon_eng.jpg',
             'cimon_eng.jpg',
             0,
             NULL,
             0,
             TO_DATE ('04/26/2017 04:19:54', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO BOARD_FILE (BO_TABLE,
                        BO_IDX,
                        BF_NO,
                        BF_FILE,
                        BF_SOURCE,
                        BF_DOWNLOAD,
                        BF_CONTENT,
                        BF_FILESIZE,
                        BF_DATETIME)
     VALUES ('portfolio',
             50,
             10,
             'samjin.jpg',
             'samjin.jpg',
             0,
             NULL,
             0,
             TO_DATE ('04/26/2017 04:19:23', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO BOARD_FILE (BO_TABLE,
                        BO_IDX,
                        BF_NO,
                        BF_FILE,
                        BF_SOURCE,
                        BF_DOWNLOAD,
                        BF_CONTENT,
                        BF_FILESIZE,
                        BF_DATETIME)
     VALUES ('portfolio',
             64,
             10,
             'jei.jpg',
             'jei.jpg',
             0,
             NULL,
             0,
             TO_DATE ('04/26/2017 05:13:21', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO BOARD_FILE (BO_TABLE,
                        BO_IDX,
                        BF_NO,
                        BF_FILE,
                        BF_SOURCE,
                        BF_DOWNLOAD,
                        BF_CONTENT,
                        BF_FILESIZE,
                        BF_DATETIME)
     VALUES ('portfolio',
             52,
             10,
             'cimon_mobile.jpg',
             'cimon_mobile.jpg',
             0,
             NULL,
             0,
             TO_DATE ('04/26/2017 05:12:12', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO BOARD_FILE (BO_TABLE,
                        BO_IDX,
                        BF_NO,
                        BF_FILE,
                        BF_SOURCE,
                        BF_DOWNLOAD,
                        BF_CONTENT,
                        BF_FILESIZE,
                        BF_DATETIME)
     VALUES ('portfolio',
             63,
             10,
             'global.jpg',
             'global.jpg',
             0,
             NULL,
             0,
             TO_DATE ('04/26/2017 05:13:31', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO BOARD_FILE (BO_TABLE,
                        BO_IDX,
                        BF_NO,
                        BF_FILE,
                        BF_SOURCE,
                        BF_DOWNLOAD,
                        BF_CONTENT,
                        BF_FILESIZE,
                        BF_DATETIME)
     VALUES ('portfolio',
             62,
             10,
             'eng.jpg',
             'eng.jpg',
             0,
             NULL,
             0,
             TO_DATE ('04/26/2017 05:13:51', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO BOARD_FILE (BO_TABLE,
                        BO_IDX,
                        BF_NO,
                        BF_FILE,
                        BF_SOURCE,
                        BF_DOWNLOAD,
                        BF_CONTENT,
                        BF_FILESIZE,
                        BF_DATETIME)
     VALUES ('portfolio',
             60,
             10,
             'hw.jpg',
             'hw.jpg',
             0,
             NULL,
             0,
             TO_DATE ('04/26/2017 05:14:15', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO BOARD_FILE (BO_TABLE,
                        BO_IDX,
                        BF_NO,
                        BF_FILE,
                        BF_SOURCE,
                        BF_DOWNLOAD,
                        BF_CONTENT,
                        BF_FILESIZE,
                        BF_DATETIME)
     VALUES ('portfolio',
             61,
             10,
             'ssro.jpg',
             'ssro.jpg',
             0,
             NULL,
             0,
             TO_DATE ('04/26/2017 05:28:02', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO BOARD_FILE (BO_TABLE,
                        BO_IDX,
                        BF_NO,
                        BF_FILE,
                        BF_SOURCE,
                        BF_DOWNLOAD,
                        BF_CONTENT,
                        BF_FILESIZE,
                        BF_DATETIME)
     VALUES ('portfolio',
             65,
             10,
             'sino.jpg',
             'sino.jpg',
             0,
             NULL,
             0,
             TO_DATE ('04/26/2017 05:28:36', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO BOARD_FILE (BO_TABLE,
                        BO_IDX,
                        BF_NO,
                        BF_FILE,
                        BF_SOURCE,
                        BF_DOWNLOAD,
                        BF_CONTENT,
                        BF_FILESIZE,
                        BF_DATETIME)
     VALUES ('portfolio',
             67,
             10,
             'kpx.jpg',
             'kpx.jpg',
             0,
             NULL,
             0,
             TO_DATE ('04/26/2017 05:28:54', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO BOARD_FILE (BO_TABLE,
                        BO_IDX,
                        BF_NO,
                        BF_FILE,
                        BF_SOURCE,
                        BF_DOWNLOAD,
                        BF_CONTENT,
                        BF_FILESIZE,
                        BF_DATETIME)
     VALUES ('portfolio',
             57,
             10,
             'ihappy.jpg',
             'ihappy.jpg',
             0,
             NULL,
             0,
             TO_DATE ('04/26/2017 05:34:34', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO BOARD_FILE (BO_TABLE,
                        BO_IDX,
                        BF_NO,
                        BF_FILE,
                        BF_SOURCE,
                        BF_DOWNLOAD,
                        BF_CONTENT,
                        BF_FILESIZE,
                        BF_DATETIME)
     VALUES ('portfolio',
             58,
             10,
             'pnb.jpg',
             'pnb.jpg',
             0,
             NULL,
             0,
             TO_DATE ('04/26/2017 05:35:00', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO BOARD_FILE (BO_TABLE,
                        BO_IDX,
                        BF_NO,
                        BF_FILE,
                        BF_SOURCE,
                        BF_DOWNLOAD,
                        BF_CONTENT,
                        BF_FILESIZE,
                        BF_DATETIME)
     VALUES ('portfolio',
             54,
             10,
             'samjin_incruit.jpg',
             'samjin_incruit.jpg',
             0,
             NULL,
             0,
             TO_DATE ('04/26/2017 05:35:29', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO BOARD_FILE (BO_TABLE,
                        BO_IDX,
                        BF_NO,
                        BF_FILE,
                        BF_SOURCE,
                        BF_DOWNLOAD,
                        BF_CONTENT,
                        BF_FILESIZE,
                        BF_DATETIME)
     VALUES ('portfolio',
             53,
             10,
             'kukje.jpg',
             'kukje.jpg',
             0,
             NULL,
             0,
             TO_DATE ('04/26/2017 05:35:54', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO BOARD_FILE (BO_TABLE,
                        BO_IDX,
                        BF_NO,
                        BF_FILE,
                        BF_SOURCE,
                        BF_DOWNLOAD,
                        BF_CONTENT,
                        BF_FILESIZE,
                        BF_DATETIME)
     VALUES ('portfolio',
             55,
             10,
             'ev.jpg',
             'ev.jpg',
             0,
             NULL,
             0,
             TO_DATE ('04/26/2017 05:37:11', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO BOARD_FILE (BO_TABLE,
                        BO_IDX,
                        BF_NO,
                        BF_FILE,
                        BF_SOURCE,
                        BF_DOWNLOAD,
                        BF_CONTENT,
                        BF_FILESIZE,
                        BF_DATETIME)
     VALUES ('portfolio',
             59,
             10,
             'mycar.jpg',
             'mycar.jpg',
             0,
             NULL,
             0,
             TO_DATE ('04/26/2017 05:37:28', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO BOARD_FILE (BO_TABLE,
                        BO_IDX,
                        BF_NO,
                        BF_FILE,
                        BF_SOURCE,
                        BF_DOWNLOAD,
                        BF_CONTENT,
                        BF_FILESIZE,
                        BF_DATETIME)
     VALUES ('portfolio',
             56,
             10,
             'sam.jpg',
             'sam.jpg',
             0,
             NULL,
             0,
             TO_DATE ('04/26/2017 05:37:46', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO BOARD_FILE (BO_TABLE,
                        BO_IDX,
                        BF_NO,
                        BF_FILE,
                        BF_SOURCE,
                        BF_DOWNLOAD,
                        BF_CONTENT,
                        BF_FILESIZE,
                        BF_DATETIME)
     VALUES ('portfolio',
             69,
             8,
             'scrap.jpg',
             'scrap.jpg',
             0,
             NULL,
             0,
             TO_DATE ('04/26/2017 06:06:25', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO BOARD_FILE (BO_TABLE,
                        BO_IDX,
                        BF_NO,
                        BF_FILE,
                        BF_SOURCE,
                        BF_DOWNLOAD,
                        BF_CONTENT,
                        BF_FILESIZE,
                        BF_DATETIME)
        VALUES (
                  'portfolio',
                  68,
                  8,
                  'screencapture-kconbiz-cafe24-program-application_credit-php-1493107810832.png',
                  'screencapture-kconbiz-cafe24-program-application_credit-php-1493107810832.png',
                  0,
                  NULL,
                  0,
                  TO_DATE ('04/26/2017 06:06:47', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO BOARD_FILE (BO_TABLE,
                        BO_IDX,
                        BF_NO,
                        BF_FILE,
                        BF_SOURCE,
                        BF_DOWNLOAD,
                        BF_CONTENT,
                        BF_FILESIZE,
                        BF_DATETIME)
     VALUES ('portfolio',
             67,
             9,
             'screencapture-kpxchemical-ir-stock-php-1493101934096.png',
             'screencapture-kpxchemical-ir-stock-php-1493101934096.png',
             0,
             NULL,
             0,
             TO_DATE ('04/26/2017 06:07:14', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO BOARD_FILE (BO_TABLE,
                        BO_IDX,
                        BF_NO,
                        BF_FILE,
                        BF_SOURCE,
                        BF_DOWNLOAD,
                        BF_CONTENT,
                        BF_FILESIZE,
                        BF_DATETIME)
     VALUES ('portfolio',
             67,
             8,
             'screencapture-kpxchemical-1493101883435.png',
             'screencapture-kpxchemical-1493101883435.png',
             0,
             NULL,
             0,
             TO_DATE ('04/26/2017 06:07:14', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO BOARD_FILE (BO_TABLE,
                        BO_IDX,
                        BF_NO,
                        BF_FILE,
                        BF_SOURCE,
                        BF_DOWNLOAD,
                        BF_CONTENT,
                        BF_FILESIZE,
                        BF_DATETIME)
     VALUES ('portfolio',
             65,
             9,
             'sino1.png',
             'sino1.png',
             0,
             NULL,
             0,
             TO_DATE ('04/26/2017 06:07:56', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO BOARD_FILE (BO_TABLE,
                        BO_IDX,
                        BF_NO,
                        BF_FILE,
                        BF_SOURCE,
                        BF_DOWNLOAD,
                        BF_CONTENT,
                        BF_FILESIZE,
                        BF_DATETIME)
     VALUES ('portfolio',
             62,
             9,
             'english_tv_03.png',
             'english_tv_03.png',
             0,
             NULL,
             0,
             TO_DATE ('04/26/2017 06:08:41', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO BOARD_FILE (BO_TABLE,
                        BO_IDX,
                        BF_NO,
                        BF_FILE,
                        BF_SOURCE,
                        BF_DOWNLOAD,
                        BF_CONTENT,
                        BF_FILESIZE,
                        BF_DATETIME)
     VALUES ('portfolio',
             62,
             8,
             'english_tv_02.png',
             'english_tv_02.png',
             0,
             NULL,
             0,
             TO_DATE ('04/26/2017 06:08:41', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO BOARD_FILE (BO_TABLE,
                        BO_IDX,
                        BF_NO,
                        BF_FILE,
                        BF_SOURCE,
                        BF_DOWNLOAD,
                        BF_CONTENT,
                        BF_FILESIZE,
                        BF_DATETIME)
        VALUES (
                  'portfolio',
                  61,
                  9,
                  'screencapture-www-jei-com-ssropen-controller-support-board-customer_online-list-php-1460010697392.png',
                  'screencapture-www-jei-com-ssropen-controller-support-board-customer_online-list-php-1460010697392.png',
                  0,
                  NULL,
                  0,
                  TO_DATE ('04/26/2017 06:10:09', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO BOARD_FILE (BO_TABLE,
                        BO_IDX,
                        BF_NO,
                        BF_FILE,
                        BF_SOURCE,
                        BF_DOWNLOAD,
                        BF_CONTENT,
                        BF_FILESIZE,
                        BF_DATETIME)
        VALUES (
                  'portfolio',
                  61,
                  8,
                  'screencapture-www-jei-com-ssropen-controller-ssropen-composition-php-1460010660098.png',
                  'screencapture-www-jei-com-ssropen-controller-ssropen-composition-php-1460010660098.png',
                  0,
                  NULL,
                  0,
                  TO_DATE ('04/26/2017 06:10:09', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO BOARD_FILE (BO_TABLE,
                        BO_IDX,
                        BF_NO,
                        BF_FILE,
                        BF_SOURCE,
                        BF_DOWNLOAD,
                        BF_CONTENT,
                        BF_FILESIZE,
                        BF_DATETIME)
     VALUES ('portfolio',
             61,
             7,
             'screencapture-www-jei-com-ssropen-1460010137363.png',
             'screencapture-www-jei-com-ssropen-1460010137363.png',
             0,
             NULL,
             0,
             TO_DATE ('04/26/2017 06:10:09', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO BOARD_FILE (BO_TABLE,
                        BO_IDX,
                        BF_NO,
                        BF_FILE,
                        BF_SOURCE,
                        BF_DOWNLOAD,
                        BF_CONTENT,
                        BF_FILESIZE,
                        BF_DATETIME)
     VALUES ('portfolio',
             60,
             9,
             'screencapture-hwaum-org-bbs-board-php-1493100983244.png',
             'screencapture-hwaum-org-bbs-board-php-1493100983244.png',
             0,
             NULL,
             0,
             TO_DATE ('04/26/2017 06:10:54', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO BOARD_FILE (BO_TABLE,
                        BO_IDX,
                        BF_NO,
                        BF_FILE,
                        BF_SOURCE,
                        BF_DOWNLOAD,
                        BF_CONTENT,
                        BF_FILESIZE,
                        BF_DATETIME)
     VALUES ('portfolio',
             60,
             8,
             'screencapture-hwaum-org-bbs-board-php-1493101001866.png',
             'screencapture-hwaum-org-bbs-board-php-1493101001866.png',
             0,
             NULL,
             0,
             TO_DATE ('04/26/2017 06:10:54', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO BOARD_FILE (BO_TABLE,
                        BO_IDX,
                        BF_NO,
                        BF_FILE,
                        BF_SOURCE,
                        BF_DOWNLOAD,
                        BF_CONTENT,
                        BF_FILESIZE,
                        BF_DATETIME)
     VALUES ('portfolio',
             60,
             7,
             'screencapture-hwaum-org-1493100941382.png',
             'screencapture-hwaum-org-1493100941382.png',
             0,
             NULL,
             0,
             TO_DATE ('04/26/2017 06:10:55', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO BOARD_FILE (BO_TABLE,
                        BO_IDX,
                        BF_NO,
                        BF_FILE,
                        BF_SOURCE,
                        BF_DOWNLOAD,
                        BF_CONTENT,
                        BF_FILESIZE,
                        BF_DATETIME)
     VALUES ('portfolio',
             68,
             10,
             'jin.jpg',
             'jin.jpg',
             0,
             NULL,
             0,
             TO_DATE ('04/26/2017 05:32:29', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO BOARD_FILE (BO_TABLE,
                        BO_IDX,
                        BF_NO,
                        BF_FILE,
                        BF_SOURCE,
                        BF_DOWNLOAD,
                        BF_CONTENT,
                        BF_FILESIZE,
                        BF_DATETIME)
     VALUES ('portfolio',
             66,
             10,
             'seoulline.jpg',
             'seoulline.jpg',
             0,
             NULL,
             0,
             TO_DATE ('04/26/2017 05:29:54', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO BOARD_FILE (BO_TABLE,
                        BO_IDX,
                        BF_NO,
                        BF_FILE,
                        BF_SOURCE,
                        BF_DOWNLOAD,
                        BF_CONTENT,
                        BF_FILESIZE,
                        BF_DATETIME)
     VALUES ('portfolio',
             69,
             10,
             'bookscrap.jpg',
             'bookscrap.jpg',
             0,
             NULL,
             0,
             TO_DATE ('04/26/2017 05:32:44', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO BOARD_FILE (BO_TABLE,
                        BO_IDX,
                        BF_NO,
                        BF_FILE,
                        BF_SOURCE,
                        BF_DOWNLOAD,
                        BF_CONTENT,
                        BF_FILESIZE,
                        BF_DATETIME)
     VALUES ('portfolio',
             54,
             9,
             'samjin_recruit4.jpg',
             'samjin_recruit4.jpg',
             0,
             NULL,
             0,
             TO_DATE ('04/26/2017 06:13:31', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO BOARD_FILE (BO_TABLE,
                        BO_IDX,
                        BF_NO,
                        BF_FILE,
                        BF_SOURCE,
                        BF_DOWNLOAD,
                        BF_CONTENT,
                        BF_FILESIZE,
                        BF_DATETIME)
     VALUES ('portfolio',
             54,
             8,
             'samjin_recruit2.jpg',
             'samjin_recruit2.jpg',
             0,
             NULL,
             0,
             TO_DATE ('04/26/2017 06:13:31', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO BOARD_FILE (BO_TABLE,
                        BO_IDX,
                        BF_NO,
                        BF_FILE,
                        BF_SOURCE,
                        BF_DOWNLOAD,
                        BF_CONTENT,
                        BF_FILESIZE,
                        BF_DATETIME)
     VALUES ('portfolio',
             54,
             7,
             'samjin_recruit1.jpg',
             'samjin_recruit1.jpg',
             0,
             NULL,
             0,
             TO_DATE ('04/26/2017 06:13:31', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO BOARD_FILE (BO_TABLE,
                        BO_IDX,
                        BF_NO,
                        BF_FILE,
                        BF_SOURCE,
                        BF_DOWNLOAD,
                        BF_CONTENT,
                        BF_FILESIZE,
                        BF_DATETIME)
     VALUES ('portfolio',
             55,
             9,
             'ev.jpg',
             'ev1.jpg',
             0,
             NULL,
             0,
             TO_DATE ('04/26/2017 06:14:08', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO BOARD_FILE (BO_TABLE,
                        BO_IDX,
                        BF_NO,
                        BF_FILE,
                        BF_SOURCE,
                        BF_DOWNLOAD,
                        BF_CONTENT,
                        BF_FILESIZE,
                        BF_DATETIME)
     VALUES ('portfolio',
             55,
             8,
             'ev03.png',
             'ev03.png',
             0,
             NULL,
             0,
             TO_DATE ('04/26/2017 06:14:08', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO BOARD_FILE (BO_TABLE,
                        BO_IDX,
                        BF_NO,
                        BF_FILE,
                        BF_SOURCE,
                        BF_DOWNLOAD,
                        BF_CONTENT,
                        BF_FILESIZE,
                        BF_DATETIME)
     VALUES ('portfolio',
             55,
             7,
             'ev.png',
             'ev.png',
             0,
             NULL,
             0,
             TO_DATE ('04/26/2017 06:14:08', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO BOARD_FILE (BO_TABLE,
                        BO_IDX,
                        BF_NO,
                        BF_FILE,
                        BF_SOURCE,
                        BF_DOWNLOAD,
                        BF_CONTENT,
                        BF_FILESIZE,
                        BF_DATETIME)
     VALUES ('portfolio',
             59,
             9,
             'diver2.png',
             'diver2.png',
             0,
             NULL,
             0,
             TO_DATE ('04/26/2017 06:28:03', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO BOARD_FILE (BO_TABLE,
                        BO_IDX,
                        BF_NO,
                        BF_FILE,
                        BF_SOURCE,
                        BF_DOWNLOAD,
                        BF_CONTENT,
                        BF_FILESIZE,
                        BF_DATETIME)
     VALUES ('portfolio',
             59,
             8,
             'diver.png',
             'diver.png',
             0,
             NULL,
             0,
             TO_DATE ('04/26/2017 06:28:03', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO BOARD_FILE (BO_TABLE,
                        BO_IDX,
                        BF_NO,
                        BF_FILE,
                        BF_SOURCE,
                        BF_DOWNLOAD,
                        BF_CONTENT,
                        BF_FILESIZE,
                        BF_DATETIME)
     VALUES ('portfolio',
             66,
             9,
             'line2.png',
             'line2.png',
             0,
             NULL,
             0,
             TO_DATE ('04/26/2017 06:28:50', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO BOARD_FILE (BO_TABLE,
                        BO_IDX,
                        BF_NO,
                        BF_FILE,
                        BF_SOURCE,
                        BF_DOWNLOAD,
                        BF_CONTENT,
                        BF_FILESIZE,
                        BF_DATETIME)
     VALUES ('portfolio',
             66,
             8,
             'line.png',
             'line.png',
             0,
             NULL,
             0,
             TO_DATE ('04/26/2017 06:28:50', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO BOARD_FILE (BO_TABLE,
                        BO_IDX,
                        BF_NO,
                        BF_FILE,
                        BF_SOURCE,
                        BF_DOWNLOAD,
                        BF_CONTENT,
                        BF_FILESIZE,
                        BF_DATETIME)
     VALUES ('portfolio',
             69,
             7,
             'bookscrap_ppt.pptx',
             'bookscrap_ppt.pptx',
             0,
             NULL,
             0,
             TO_DATE ('04/26/2017 06:34:21', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO LOGIN (LO_IP,
                   MB_ID,
                   LO_REGDATE,
                   LO_LOCATION,
                   LO_URL)
     VALUES ('127.0.0.1',
             NULL,
             TO_DATE ('03/25/2017 14:19:48', 'MM/DD/YYYY HH24:MI:SS'),
             '537.',
             '/mvc_project/adm/login/loginOK.do');

INSERT INTO LOGIN (LO_IP,
                   MB_ID,
                   LO_REGDATE,
                   LO_LOCATION,
                   LO_URL)
     VALUES ('127.0.0.1',
             NULL,
             TO_DATE ('03/25/2017 14:20:08', 'MM/DD/YYYY HH24:MI:SS'),
             '537.',
             '/mvc_project/adm/login/loginOK.do');

INSERT INTO LOGIN (LO_IP,
                   MB_ID,
                   LO_REGDATE,
                   LO_LOCATION,
                   LO_URL)
     VALUES ('127.0.0.1',
             NULL,
             TO_DATE ('03/25/2017 14:22:57', 'MM/DD/YYYY HH24:MI:SS'),
             '537.',
             '/mvc_project/adm/login/loginOK.do');

INSERT INTO LOGIN (LO_IP,
                   MB_ID,
                   LO_REGDATE,
                   LO_LOCATION,
                   LO_URL)
     VALUES ('127.0.0.1',
             NULL,
             TO_DATE ('03/25/2017 14:25:06', 'MM/DD/YYYY HH24:MI:SS'),
             '537.',
             '/mvc_project/adm/login/loginOK.do');

INSERT INTO LOGIN (LO_IP,
                   MB_ID,
                   LO_REGDATE,
                   LO_LOCATION,
                   LO_URL)
     VALUES ('127.0.0.1',
             NULL,
             TO_DATE ('03/25/2017 14:26:04', 'MM/DD/YYYY HH24:MI:SS'),
             '537.',
             '/mvc_project/adm/login/loginOK.do');

INSERT INTO LOGIN (LO_IP,
                   MB_ID,
                   LO_REGDATE,
                   LO_LOCATION,
                   LO_URL)
     VALUES ('127.0.0.1',
             NULL,
             TO_DATE ('03/25/2017 14:27:18', 'MM/DD/YYYY HH24:MI:SS'),
             '537.',
             '/mvc_project/adm/login/loginOK.do');

INSERT INTO LOGIN (LO_IP,
                   MB_ID,
                   LO_REGDATE,
                   LO_LOCATION,
                   LO_URL)
     VALUES ('127.0.0.1',
             NULL,
             TO_DATE ('03/26/2017 15:38:27', 'MM/DD/YYYY HH24:MI:SS'),
             '537.',
             '/mvc_project/adm/login/loginOK.do');

INSERT INTO LOGIN (LO_IP,
                   MB_ID,
                   LO_REGDATE,
                   LO_LOCATION,
                   LO_URL)
     VALUES ('127.0.0.1',
             NULL,
             TO_DATE ('03/27/2017 16:44:32', 'MM/DD/YYYY HH24:MI:SS'),
             '537.',
             '/mvc_project/adm/login/loginOK.do');

INSERT INTO LOGIN (LO_IP,
                   MB_ID,
                   LO_REGDATE,
                   LO_LOCATION,
                   LO_URL)
     VALUES ('127.0.0.1',
             NULL,
             TO_DATE ('03/28/2017 16:55:00', 'MM/DD/YYYY HH24:MI:SS'),
             '537.',
             '/mvc_project/adm/login/loginOK.do');

INSERT INTO LOGIN (LO_IP,
                   MB_ID,
                   LO_REGDATE,
                   LO_LOCATION,
                   LO_URL)
     VALUES ('127.0.0.1',
             NULL,
             TO_DATE ('04/11/2017 11:58:27', 'MM/DD/YYYY HH24:MI:SS'),
             '537.',
             '/mvc_project/adm/login/loginOK.do');

INSERT INTO LOGIN (LO_IP,
                   MB_ID,
                   LO_REGDATE,
                   LO_LOCATION,
                   LO_URL)
     VALUES ('127.0.0.1',
             NULL,
             TO_DATE ('04/17/2017 10:10:01', 'MM/DD/YYYY HH24:MI:SS'),
             '537.',
             '/mvc_project/adm/login/loginOK.do');

INSERT INTO LOGIN (LO_IP,
                   MB_ID,
                   LO_REGDATE,
                   LO_LOCATION,
                   LO_URL)
     VALUES ('127.0.0.1',
             NULL,
             TO_DATE ('04/17/2017 13:05:10', 'MM/DD/YYYY HH24:MI:SS'),
             ' 7.0',
             '/mvc_project/adm/login/loginOK.do');

INSERT INTO LOGIN (LO_IP,
                   MB_ID,
                   LO_REGDATE,
                   LO_LOCATION,
                   LO_URL)
     VALUES ('127.0.0.1',
             NULL,
             TO_DATE ('04/18/2017 10:46:47', 'MM/DD/YYYY HH24:MI:SS'),
             '537.',
             '/mvc_project/adm/login/loginOK.do');

INSERT INTO LOGIN (LO_IP,
                   MB_ID,
                   LO_REGDATE,
                   LO_LOCATION,
                   LO_URL)
     VALUES ('127.0.0.1',
             NULL,
             TO_DATE ('04/19/2017 12:42:18', 'MM/DD/YYYY HH24:MI:SS'),
             '537.',
             '/mvc_project/adm/login/loginOK.do');

INSERT INTO LOGIN (LO_IP,
                   MB_ID,
                   LO_REGDATE,
                   LO_LOCATION,
                   LO_URL)
     VALUES ('127.0.0.1',
             NULL,
             TO_DATE ('04/19/2017 16:41:40', 'MM/DD/YYYY HH24:MI:SS'),
             '537.',
             '/mvc_project/adm/login/loginOK.do');

INSERT INTO LOGIN (LO_IP,
                   MB_ID,
                   LO_REGDATE,
                   LO_LOCATION,
                   LO_URL)
     VALUES ('127.0.0.1',
             NULL,
             TO_DATE ('04/20/2017 18:49:31', 'MM/DD/YYYY HH24:MI:SS'),
             '537.',
             '/mvc_project/adm/login/loginOK.do');

INSERT INTO LOGIN (LO_IP,
                   MB_ID,
                   LO_REGDATE,
                   LO_LOCATION,
                   LO_URL)
     VALUES ('127.0.0.1',
             NULL,
             TO_DATE ('04/21/2017 22:09:32', 'MM/DD/YYYY HH24:MI:SS'),
             '537.',
             '/mvc_project/adm/login/loginOK.do');

INSERT INTO LOGIN (LO_IP,
                   MB_ID,
                   LO_REGDATE,
                   LO_LOCATION,
                   LO_URL)
     VALUES ('127.0.0.1',
             NULL,
             TO_DATE ('04/23/2017 09:36:01', 'MM/DD/YYYY HH24:MI:SS'),
             '537.',
             '/mvc_project/adm/login/loginOK.do');

INSERT INTO LOGIN (LO_IP,
                   MB_ID,
                   LO_REGDATE,
                   LO_LOCATION,
                   LO_URL)
     VALUES ('121.160.41.129',
             NULL,
             TO_DATE ('04/25/2017 05:58:00', 'MM/DD/YYYY HH24:MI:SS'),
             '537.',
             '/mvc_project/adm/login/loginOK.do');

INSERT INTO LOGIN (LO_IP,
                   MB_ID,
                   LO_REGDATE,
                   LO_LOCATION,
                   LO_URL)
     VALUES ('121.160.41.129',
             NULL,
             TO_DATE ('04/26/2017 06:02:00', 'MM/DD/YYYY HH24:MI:SS'),
             '537.',
             '/mvc_project/adm/login/loginOK.do');

INSERT INTO LOGIN (LO_IP,
                   MB_ID,
                   LO_REGDATE,
                   LO_LOCATION,
                   LO_URL)
     VALUES ('121.160.177.76',
             NULL,
             TO_DATE ('05/09/2017 08:34:49', 'MM/DD/YYYY HH24:MI:SS'),
             '537.',
             '/mvc_project/adm/login/loginOK.do');

INSERT INTO LOGIN (LO_IP,
                   MB_ID,
                   LO_REGDATE,
                   LO_LOCATION,
                   LO_URL)
     VALUES ('121.160.176.58',
             NULL,
             TO_DATE ('05/25/2017 13:18:06', 'MM/DD/YYYY HH24:MI:SS'),
             '537.',
             '/mvc_project/adm/login/loginOK.do');

INSERT INTO MENU (ME_IDX,
                  ME_NUM,
                  ME_CODE,
                  ME_NAME,
                  ME_LINK,
                  ME_IS_VIEW,
                  ME_IS_TARGET,
                  ME_CONTENT)
     VALUES (1,
             0,
             '10',
             'HOME',
             '/pf/index.do',
             1,
             0,
             'HOME');

INSERT INTO MENU (ME_IDX,
                  ME_NUM,
                  ME_CODE,
                  ME_NAME,
                  ME_LINK,
                  ME_IS_VIEW,
                  ME_IS_TARGET,
                  ME_CONTENT)
     VALUES (17,
             3,
             '30',
             'NOTICE',
             '/pf/board/list.do?bo_table=notice',
             0,
             1,
             '공지사항게시판');

INSERT INTO MENU (ME_IDX,
                  ME_NUM,
                  ME_CODE,
                  ME_NAME,
                  ME_LINK,
                  ME_IS_VIEW,
                  ME_IS_TARGET,
                  ME_CONTENT)
     VALUES (18,
             4,
             '40',
             'Q&A',
             '/pf/board/list.do?bo_table=qna',
             1,
             1,
             ' ');

INSERT INTO MENU (ME_IDX,
                  ME_NUM,
                  ME_CODE,
                  ME_NAME,
                  ME_LINK,
                  ME_IS_VIEW,
                  ME_IS_TARGET,
                  ME_CONTENT)
     VALUES (15,
             1,
             '20',
             'ABOUT',
             '/pf/page/about',
             1,
             0,
             ' ');

INSERT INTO MENU (ME_IDX,
                  ME_NUM,
                  ME_CODE,
                  ME_NAME,
                  ME_LINK,
                  ME_IS_VIEW,
                  ME_IS_TARGET,
                  ME_CONTENT)
     VALUES (19,
             2,
             '50',
             'PORTFOLIO',
             '/pf/board/list.do?bo_table=portfolio',
             1,
             1,
             ' ');

INSERT INTO MENU (ME_IDX,
                  ME_NUM,
                  ME_CODE,
                  ME_NAME,
                  ME_LINK,
                  ME_IS_VIEW,
                  ME_IS_TARGET,
                  ME_CONTENT)
     VALUES (20,
             5,
             '60',
             'CONTACT',
             '/pf/page/contact',
             1,
             1,
             ' ');

INSERT INTO BOARD_PORTFOLIO (BO_IDX,
                             BO_WRITER,
                             BO_MEMBER,
                             BO_SUBJECT,
                             BO_CONTENT,
                             BO_IS_SECRET,
                             BO_IS_NOTICE,
                             BO_FILE,
                             BO_PASS,
                             BO_REF,
                             BO_LEVEL,
                             BO_STEP,
                             BO_HIT,
                             BO_REGDATE,
                             BO_IS_VIEW,
                             BO_IP,
                             BO_1,
                             BO_2,
                             BO_3,
                             BO_4,
                             BO_5,
                             BO_TAG)
        VALUES (
                  50,
                  '관리자',
                  NULL,
                  '(주)삼진제약 홈페이지 리뉴얼 및 웹접근성 마크 획득 프로젝트',
                  '1) 소속업체 : (주)윅슨어소시에이츠
2) 의뢰업체 : (주)삼진제약
3) 목표 : 리뉴얼 및 웹접근성 마크 획득
4) 구성원 : 4
5) 참여도 : 100%
6) 담당업무 : 퍼블리싱(메인 및 서브 전체 담당)
7) URL : http://www.samjinpharm.co.kr/
삼진제약 홈페이지 리뉴얼 및 웹접근성 마크 획득 프로젝트로 진행하였습니
다. 국문 영문 메인 서브 페이지, 웹표준 퍼블리싱, 크로스브라우징작업을 수
행하였습니다.',
                  0,
                  0,
                  '1',
                  '3fbbb66bdbfef670ab96d46cef31e49fa9298894629b9e99b65a070b8b83f169',
                  50,
                  0,
                  1,
                  6,
                  TO_DATE ('04/23/2017 15:57:24', 'MM/DD/YYYY HH24:MI:SS'),
                  1,
                  NULL,
                  '100',
                  '2013-11-01',
                  '2014-01-01',
                  'javascript, HTML, CSS, jQuery, ASP',
                  'http://www.samjinpharm.co.kr/',
                  '#삼진제약, #웹, #웹퍼블리싱');

INSERT INTO BOARD_PORTFOLIO (BO_IDX,
                             BO_WRITER,
                             BO_MEMBER,
                             BO_SUBJECT,
                             BO_CONTENT,
                             BO_IS_SECRET,
                             BO_IS_NOTICE,
                             BO_FILE,
                             BO_PASS,
                             BO_REF,
                             BO_LEVEL,
                             BO_STEP,
                             BO_HIT,
                             BO_REGDATE,
                             BO_IS_VIEW,
                             BO_IP,
                             BO_1,
                             BO_2,
                             BO_3,
                             BO_4,
                             BO_5,
                             BO_TAG)
        VALUES (
                  51,
                  '관리자',
                  NULL,
                  '(주)사이몬 영문 웹사이트 리뉴얼 프로젝트',
                  '1) 소속업체 : (주)윅슨어소시에이츠
2) 의뢰업체 : (주)사이몬
3) 목표 : 웹사이트 리뉴얼
4) 구성원 : 3
5) 참여도 : 100%
6) 담당업무 : 퍼블리싱(메인 및 서브 전체 담당)

기존 (주)사이몬 영문 사이트를 리뉴얼 한 프로젝트 입니다. 웹표준 코딩으로
메인, 서브 jQuery, javaScript 작업을 하였습니다.
'                  ,
                  0,
                  0,
                  '1',
                  '3fbbb66bdbfef670ab96d46cef31e49fa9298894629b9e99b65a070b8b83f169',
                  51,
                  0,
                  1,
                  2,
                  TO_DATE ('04/23/2017 16:14:11', 'MM/DD/YYYY HH24:MI:SS'),
                  1,
                  NULL,
                  '100',
                  '2014-06-01',
                  '2014-06-30',
                  'ASP, HTML,  javascript, CSS',
                  'http://www.cimon.com/eng/',
                  '#Cimon, #웹, #웹퍼블리싱');

INSERT INTO BOARD_PORTFOLIO (BO_IDX,
                             BO_WRITER,
                             BO_MEMBER,
                             BO_SUBJECT,
                             BO_CONTENT,
                             BO_IS_SECRET,
                             BO_IS_NOTICE,
                             BO_FILE,
                             BO_PASS,
                             BO_REF,
                             BO_LEVEL,
                             BO_STEP,
                             BO_HIT,
                             BO_REGDATE,
                             BO_IS_VIEW,
                             BO_IP,
                             BO_1,
                             BO_2,
                             BO_3,
                             BO_4,
                             BO_5,
                             BO_TAG)
        VALUES (
                  52,
                  '관리자',
                  NULL,
                  '(주)사이몬 국,영문 모바일 웹사이트',
                  '1) 소속업체 : (주)윅슨어소시에이츠
2) 의뢰업체 : (주)사이몬
3) 목표 : 국,영문 모바일 웹사이트
4) 구성원 : 3
5) 참여도 : 100%
6) 담당업무 : 퍼블리싱(메인 및 서브 전체 담당)',
                  0,
                  0,
                  '1',
                  '3fbbb66bdbfef670ab96d46cef31e49fa9298894629b9e99b65a070b8b83f169',
                  52,
                  0,
                  1,
                  0,
                  TO_DATE ('04/23/2017 23:12:12', 'MM/DD/YYYY HH24:MI:SS'),
                  1,
                  NULL,
                  '100',
                  '2014-07-01',
                  '2014-08-18',
                  'javascript, HTML, CSS, jQuery, ASP',
                  'http://m.cimon.com/',
                  '#Cimon, #모바일, #모바일퍼블리싱');

INSERT INTO BOARD_PORTFOLIO (BO_IDX,
                             BO_WRITER,
                             BO_MEMBER,
                             BO_SUBJECT,
                             BO_CONTENT,
                             BO_IS_SECRET,
                             BO_IS_NOTICE,
                             BO_FILE,
                             BO_PASS,
                             BO_REF,
                             BO_LEVEL,
                             BO_STEP,
                             BO_HIT,
                             BO_REGDATE,
                             BO_IS_VIEW,
                             BO_IP,
                             BO_1,
                             BO_2,
                             BO_3,
                             BO_4,
                             BO_5,
                             BO_TAG)
        VALUES (
                  53,
                  '관리자',
                  NULL,
                  '(주)국제약품 반응형웹 워드프레스 프로젝트',
                  '1) 소속업체 : (주)윅슨어소시에이츠
2) 의뢰업체 : (주)국제약품
3) 목표 : 국제약품 반응형웹 워드프레스 리뉴얼 프로젝트
4) 구성원 : 4
5) 참여도 : 100%
6) 담당업무 : 퍼블리싱(메인 및 서브 전체 담당)

국제약품 측에서 워드프레스로 사이트 구축을 진행하고자 하여 워드프레스 테마를 구입한 뒤 커스텀하여 구축한 사이트입니다.
반응형웹 작업으로 국문과 영문 페이지 모두 웹표준 마크업으로 진행되었습니다.',
                  0,
                  0,
                  '1',
                  '3fbbb66bdbfef670ab96d46cef31e49fa9298894629b9e99b65a070b8b83f169',
                  53,
                  0,
                  1,
                  1,
                  TO_DATE ('04/23/2017 23:21:29', 'MM/DD/YYYY HH24:MI:SS'),
                  1,
                  NULL,
                  '100',
                  '2014-08-01',
                  '2014-09-17',
                  'PHP, HTML, 워드프레스, javascript, CSS',
                  'http://www.kukjepharm.co.kr/',
                  '#국제약품, #웹, #웹퍼블리싱, #워드프레스');

INSERT INTO BOARD_PORTFOLIO (BO_IDX,
                             BO_WRITER,
                             BO_MEMBER,
                             BO_SUBJECT,
                             BO_CONTENT,
                             BO_IS_SECRET,
                             BO_IS_NOTICE,
                             BO_FILE,
                             BO_PASS,
                             BO_REF,
                             BO_LEVEL,
                             BO_STEP,
                             BO_HIT,
                             BO_REGDATE,
                             BO_IS_VIEW,
                             BO_IP,
                             BO_1,
                             BO_2,
                             BO_3,
                             BO_4,
                             BO_5,
                             BO_TAG)
        VALUES (
                  54,
                  '관리자',
                  NULL,
                  '(주)삼진제약 입사지원 웹사이트',
                  '1) 소속업체 : (주)윅슨어소시에이츠
2) 의뢰업체 : (주)삼진제약
3) 목표 : 삼진제약 온라인 입사지원 웹사이트 구축
4) 구성원 : 4
5) 참여도 : 100%
6) 담당업무 : 퍼블리싱(메인 및 서브 전체 담당)

웹표준, 크로스브라우징 작업, 메인 및 서브, 관리자 사이트 퍼블리싱 작업을
진행하였습니다. 입사지원을 위한 웹사이트 제작으로 폼과 관련된 마크업 작
업이 주를 이뤘던 프로젝트 였습니다
'                  ,
                  0,
                  0,
                  '5',
                  '3fbbb66bdbfef670ab96d46cef31e49fa9298894629b9e99b65a070b8b83f169',
                  54,
                  0,
                  1,
                  2,
                  TO_DATE ('04/23/2017 23:29:11', 'MM/DD/YYYY HH24:MI:SS'),
                  1,
                  NULL,
                  '100',
                  '2014-03-01',
                  '2014-04-21',
                  'ASP, HTML,  javascript, CSS',
                  'http://www.samjinpharm.co.kr/SJ_recruit/',
                  '#삼진제약, #웹, #웹퍼블리싱');

INSERT INTO BOARD_PORTFOLIO (BO_IDX,
                             BO_WRITER,
                             BO_MEMBER,
                             BO_SUBJECT,
                             BO_CONTENT,
                             BO_IS_SECRET,
                             BO_IS_NOTICE,
                             BO_FILE,
                             BO_PASS,
                             BO_REF,
                             BO_LEVEL,
                             BO_STEP,
                             BO_HIT,
                             BO_REGDATE,
                             BO_IS_VIEW,
                             BO_IP,
                             BO_1,
                             BO_2,
                             BO_3,
                             BO_4,
                             BO_5,
                             BO_TAG)
        VALUES (
                  55,
                  '관리자',
                  NULL,
                  'BMW 전기 충전소 하이브리드앱 개발 프로젝트',
                  '1) 소속업체 : (주)윅슨어소시에이츠
2) 의뢰업체 : (주)pmgrow
3) 목표 : 국,영문 모바일 웹사이트
4) 구성원 : 3
5) 참여도 : 100%
6) 담당업무 : 퍼블리싱(메인 및 서브 전체 담당)

전기충전소 앱 개발 프로젝트로  하이브리드 앱으로 개발하여 HTML5, CSS3 퍼블리싱으로 투입되었던 프로젝트 입니다. 원페이지로 작업하여 CSS3 opacity, 트랜지션, 애니메이션으로 jQuery animate 작업을
대신하였습니다.
'                  ,
                  0,
                  0,
                  '5',
                  '3fbbb66bdbfef670ab96d46cef31e49fa9298894629b9e99b65a070b8b83f169',
                  55,
                  0,
                  1,
                  2,
                  TO_DATE ('04/23/2017 23:34:17', 'MM/DD/YYYY HH24:MI:SS'),
                  1,
                  NULL,
                  '100',
                  '2014-07-01',
                  '2014-07-29',
                  'Android, HTML,  javascript, CSS',
                  NULL,
                  '#하이브리드앱, #모바일, #전기충전소');

INSERT INTO BOARD_PORTFOLIO (BO_IDX,
                             BO_WRITER,
                             BO_MEMBER,
                             BO_SUBJECT,
                             BO_CONTENT,
                             BO_IS_SECRET,
                             BO_IS_NOTICE,
                             BO_FILE,
                             BO_PASS,
                             BO_REF,
                             BO_LEVEL,
                             BO_STEP,
                             BO_HIT,
                             BO_REGDATE,
                             BO_IS_VIEW,
                             BO_IP,
                             BO_1,
                             BO_2,
                             BO_3,
                             BO_4,
                             BO_5,
                             BO_TAG)
        VALUES (
                  56,
                  '관리자',
                  NULL,
                  '(주)샘컴퍼니 웹사이트 리뉴얼 프로젝트',
                  '1) 소속업체 : (주)윅슨어소시에이츠
2) 의뢰업체 : (주)샘컴퍼니
3) 목표 : 웹사이트 리뉴얼
4) 구성원 : 3
5) 참여도 : 100%
6) 담당업무 : 퍼블리싱(메인 및 서브 전체 담당)

연예인 기획사인 샘컴퍼니 리뉴얼 웹사이트 구축 프로젝트로, 웹표준 마크업, 메인 및 서브 UX JavaScript, jQuery 작업을 진행하였습니다. 서브페이지는 모두 스크롤로 움직이는 원 페이지 방식으로 제작되었습니다.
'                  ,
                  0,
                  0,
                  '1',
                  '3fbbb66bdbfef670ab96d46cef31e49fa9298894629b9e99b65a070b8b83f169',
                  56,
                  0,
                  1,
                  4,
                  TO_DATE ('04/23/2017 23:38:25', 'MM/DD/YYYY HH24:MI:SS'),
                  1,
                  NULL,
                  '100',
                  '2015-04-02',
                  '2015-04-29',
                  'ASP, HTML,  javascript, CSS',
                  'http://www.semcompany.co.kr/',
                  '#샘컴퍼니, #웹, #웹퍼블리싱');

INSERT INTO BOARD_PORTFOLIO (BO_IDX,
                             BO_WRITER,
                             BO_MEMBER,
                             BO_SUBJECT,
                             BO_CONTENT,
                             BO_IS_SECRET,
                             BO_IS_NOTICE,
                             BO_FILE,
                             BO_PASS,
                             BO_REF,
                             BO_LEVEL,
                             BO_STEP,
                             BO_HIT,
                             BO_REGDATE,
                             BO_IS_VIEW,
                             BO_IP,
                             BO_1,
                             BO_2,
                             BO_3,
                             BO_4,
                             BO_5,
                             BO_TAG)
        VALUES (
                  57,
                  '관리자',
                  NULL,
                  '아이행복카드 마이크로 웹&모바일 사이트',
                  '1) 소속업체 : (주)윅슨어소시에이츠
2) 의뢰업체 : 아이행복카드
3) 목표 : 마이크로 웹&모바일 사이트
4) 구성원 : 3
5) 참여도 : 100%
6) 담당업무 : 퍼블리싱(메인 및 서브 전체 담당)

아이행복카드를 소개하는 마이크로 사이트 구축 프로젝트 입니다. youtube api 를 이용하여 광고 동영상을 컨트롤 하는 스크립트를 코딩하였습니다.
'                  ,
                  0,
                  0,
                  '1',
                  '3fbbb66bdbfef670ab96d46cef31e49fa9298894629b9e99b65a070b8b83f169',
                  57,
                  0,
                  1,
                  3,
                  TO_DATE ('04/23/2017 23:43:05', 'MM/DD/YYYY HH24:MI:SS'),
                  1,
                  NULL,
                  '100',
                  '2015-04-04',
                  '2015-04-29',
                  'ASP, HTML,  javascript, CSS',
                  ' http://ihappycard.kr/',
                  '#아이행복카드, #웹, #웹퍼블리싱');

INSERT INTO BOARD_PORTFOLIO (BO_IDX,
                             BO_WRITER,
                             BO_MEMBER,
                             BO_SUBJECT,
                             BO_CONTENT,
                             BO_IS_SECRET,
                             BO_IS_NOTICE,
                             BO_FILE,
                             BO_PASS,
                             BO_REF,
                             BO_LEVEL,
                             BO_STEP,
                             BO_HIT,
                             BO_REGDATE,
                             BO_IS_VIEW,
                             BO_IP,
                             BO_1,
                             BO_2,
                             BO_3,
                             BO_4,
                             BO_5,
                             BO_TAG)
        VALUES (
                  58,
                  '관리자',
                  NULL,
                  '국제 P&B 쇼핑몰제작',
                  '1) 소속업체 : (주)윅슨어소시에이츠
2) 의뢰업체 : 국제P&B
3) 목표 : 고도몰 국제 P&B제품 판매 웹사이트
4) 구성원 : 3명
5) 참여도 : 100%
6) 담당업무 : 웹퍼블리싱
'                  ,
                  0,
                  0,
                  '1',
                  '3fbbb66bdbfef670ab96d46cef31e49fa9298894629b9e99b65a070b8b83f169',
                  58,
                  0,
                  1,
                  0,
                  TO_DATE ('04/25/2017 06:11:15', 'MM/DD/YYYY HH24:MI:SS'),
                  1,
                  NULL,
                  '100',
                  '2015-05-05',
                  '2015-05-28',
                  'javascript, HTML, CSS, jQuery, PHP',
                  'http://pnbstore.com/',
                  '#고도몰, #국제P&B, #쇼핑몰, #웹사이트, #웹퍼블리싱');

INSERT INTO BOARD_PORTFOLIO (BO_IDX,
                             BO_WRITER,
                             BO_MEMBER,
                             BO_SUBJECT,
                             BO_CONTENT,
                             BO_IS_SECRET,
                             BO_IS_NOTICE,
                             BO_FILE,
                             BO_PASS,
                             BO_REF,
                             BO_LEVEL,
                             BO_STEP,
                             BO_HIT,
                             BO_REGDATE,
                             BO_IS_VIEW,
                             BO_IP,
                             BO_1,
                             BO_2,
                             BO_3,
                             BO_4,
                             BO_5,
                             BO_TAG)
        VALUES (
                  59,
                  '관리자',
                  NULL,
                  '마이카드라이브 웹사이트제작',
                  '1) 소속업체 : (주)윅슨어소시에이츠
2) 의뢰업체 : 마이카드라이브
3) 목표 : 운전연수 웹사이트 제작
4) 구성원 : 2명
5) 참여도 : 100%
6) 담당업무 : 전체 페이지 퍼블리싱, 그누보드 커스텀 개발

그누보드를 커스텀하여 개발 및 프론트단을 모두 작업한 프로젝트 입니다.
PHP, mysql를 작업하면서 백엔드 작업에 대해 알 수 있었던 프로젝트였습니
다.'              ,
                  0,
                  0,
                  '4',
                  '3fbbb66bdbfef670ab96d46cef31e49fa9298894629b9e99b65a070b8b83f169',
                  59,
                  0,
                  1,
                  0,
                  TO_DATE ('04/25/2017 06:13:32', 'MM/DD/YYYY HH24:MI:SS'),
                  1,
                  NULL,
                  '100',
                  '2015-07-07',
                  '2017-07-25',
                  'PHP, HTML, 그누보드, javascript, CSS',
                  'http://mcdrive.net/',
                  '#웹, #웹퍼블리싱, #마이카드라이브');

INSERT INTO BOARD_PORTFOLIO (BO_IDX,
                             BO_WRITER,
                             BO_MEMBER,
                             BO_SUBJECT,
                             BO_CONTENT,
                             BO_IS_SECRET,
                             BO_IS_NOTICE,
                             BO_FILE,
                             BO_PASS,
                             BO_REF,
                             BO_LEVEL,
                             BO_STEP,
                             BO_HIT,
                             BO_REGDATE,
                             BO_IS_VIEW,
                             BO_IP,
                             BO_1,
                             BO_2,
                             BO_3,
                             BO_4,
                             BO_5,
                             BO_TAG)
        VALUES (
                  60,
                  '관리자',
                  NULL,
                  '화음뮤지엄 리뉴얼',
                  '1) 소속업체 : (주)윅슨어소시에이츠 (프리랜서)
2) 의뢰업체 : 화음뮤지엄
3) 목표 : 웹사이트 리뉴얼 퍼블리싱 , 개발
4) 구성원 : 2명
5) 참여도 : 100%
6) 담당업무 : 퍼블리싱 , 개발',
                  0,
                  0,
                  '5',
                  '3fbbb66bdbfef670ab96d46cef31e49fa9298894629b9e99b65a070b8b83f169',
                  60,
                  0,
                  1,
                  2,
                  TO_DATE ('04/25/2017 06:20:25', 'MM/DD/YYYY HH24:MI:SS'),
                  1,
                  NULL,
                  '100',
                  '2016-08-13',
                  '2016-08-31',
                  'PHP, HTML, 그누보드, javascript, CSS',
                  'http://www.hwaum.org/',
                  '#화음, #웹, #반응형, #웹퍼블리싱, #웹개발');

INSERT INTO BOARD_PORTFOLIO (BO_IDX,
                             BO_WRITER,
                             BO_MEMBER,
                             BO_SUBJECT,
                             BO_CONTENT,
                             BO_IS_SECRET,
                             BO_IS_NOTICE,
                             BO_FILE,
                             BO_PASS,
                             BO_REF,
                             BO_LEVEL,
                             BO_STEP,
                             BO_HIT,
                             BO_REGDATE,
                             BO_IS_VIEW,
                             BO_IP,
                             BO_1,
                             BO_2,
                             BO_3,
                             BO_4,
                             BO_5,
                             BO_TAG)
        VALUES (
                  61,
                  '관리자',
                  NULL,
                  '재능스스로펜 리뉴얼',
                  '1) 소속업체 : (주)재능E아카데미
2) 의뢰업체 : (주)재능E아카데미
3) 목표 : 기존 스스로펜 사이트 리뉴얼
4) 구성원 : 4명
5) 참여도 : 80%
6) 담당업무 : 웹퍼블리싱',
                  0,
                  0,
                  '5',
                  '3fbbb66bdbfef670ab96d46cef31e49fa9298894629b9e99b65a070b8b83f169',
                  61,
                  0,
                  1,
                  3,
                  TO_DATE ('04/25/2017 06:43:43', 'MM/DD/YYYY HH24:MI:SS'),
                  1,
                  NULL,
                  '80',
                  '2015-04-09',
                  '2015-10-28',
                  'PHP, HTML, jQuery, javascript,My-SQL',
                  'http://www.jei.com/ssropen/',
                  '#웹, #웹퍼블리싱, #재능');

INSERT INTO BOARD_PORTFOLIO (BO_IDX,
                             BO_WRITER,
                             BO_MEMBER,
                             BO_SUBJECT,
                             BO_CONTENT,
                             BO_IS_SECRET,
                             BO_IS_NOTICE,
                             BO_FILE,
                             BO_PASS,
                             BO_REF,
                             BO_LEVEL,
                             BO_STEP,
                             BO_HIT,
                             BO_REGDATE,
                             BO_IS_VIEW,
                             BO_IP,
                             BO_1,
                             BO_2,
                             BO_3,
                             BO_4,
                             BO_5,
                             BO_TAG)
        VALUES (
                  62,
                  '관리자',
                  NULL,
                  '재능잉글리쉬 영어를 부탁해 마이크로 사이트',
                  '1) 소속업체 : (주)재능E아카데미
2) 의뢰업체 : (주)재능E아카데미
3) 목표 : 재능잉글리쉬 영어를 부탁해 마이크로 사이트 제작
4) 구성원 : 4명
5) 참여도 : 100%
6) 담당업무 : 웹퍼블리싱

제능잉글리쉬tv 에서 영어를 부탁해 라는 프로그램을 소개하는 마이크로 웹사
이트를 제작하는 프로젝트를 진행하였습니다.
'                  ,
                  0,
                  0,
                  '4',
                  '3fbbb66bdbfef670ab96d46cef31e49fa9298894629b9e99b65a070b8b83f169',
                  62,
                  0,
                  1,
                  3,
                  TO_DATE ('04/25/2017 06:49:37', 'MM/DD/YYYY HH24:MI:SS'),
                  1,
                  NULL,
                  '100',
                  '2015-09-02',
                  '2015-09-23',
                  'ASP, HTML, CSS, javascript',
                  'http://www.jeienglishtv.com/creation/index.asp',
                  '#재능, #웹퍼블리싱, #재능E아카데이');

INSERT INTO BOARD_PORTFOLIO (BO_IDX,
                             BO_WRITER,
                             BO_MEMBER,
                             BO_SUBJECT,
                             BO_CONTENT,
                             BO_IS_SECRET,
                             BO_IS_NOTICE,
                             BO_FILE,
                             BO_PASS,
                             BO_REF,
                             BO_LEVEL,
                             BO_STEP,
                             BO_HIT,
                             BO_REGDATE,
                             BO_IS_VIEW,
                             BO_IP,
                             BO_1,
                             BO_2,
                             BO_3,
                             BO_4,
                             BO_5,
                             BO_TAG)
        VALUES (
                  63,
                  '관리자',
                  NULL,
                  '재능글로벌 웹사이트 리뉴얼',
                  '1) 소속업체 : (주)재능E아카데미
2) 의뢰업체 : (주)재능E아카데미
3) 목표 : 기존 재능글로벌 사이트 리뉴얼
4) 구성원 : 6명
5) 참여도 : 100%
6) 담당업무 : 웹퍼블리싱

기존 해외에서 사용하는 회원관리 웹 사이트를 리뉴얼 하는 작업을 맡았습니
다. jsp로 진행되어 이클립스, git 를 사용하였으며 3개월에 걸친 프로젝트로
많은 페이지 퍼블리싱, 수정 및 개발 작업으로 CSS 재사용 및 사용자가 접근
하기 쉬운 UI / UX 구성에 대해 한번 더 생각 할 수 있게 해준 프로젝트입니
다'               ,
                  0,
                  0,
                  '1',
                  '3fbbb66bdbfef670ab96d46cef31e49fa9298894629b9e99b65a070b8b83f169',
                  63,
                  0,
                  1,
                  5,
                  TO_DATE ('04/25/2017 06:54:03', 'MM/DD/YYYY HH24:MI:SS'),
                  1,
                  NULL,
                  '100',
                  '2015-09-01',
                  '2015-12-23',
                  'jSP, CSS, HTML, javascript',
                  'http://bms.jei-global.com/',
                  '#웹퍼블리싱, #재능, #글로벌');

INSERT INTO BOARD_PORTFOLIO (BO_IDX,
                             BO_WRITER,
                             BO_MEMBER,
                             BO_SUBJECT,
                             BO_CONTENT,
                             BO_IS_SECRET,
                             BO_IS_NOTICE,
                             BO_FILE,
                             BO_PASS,
                             BO_REF,
                             BO_LEVEL,
                             BO_STEP,
                             BO_HIT,
                             BO_REGDATE,
                             BO_IS_VIEW,
                             BO_IP,
                             BO_1,
                             BO_2,
                             BO_3,
                             BO_4,
                             BO_5,
                             BO_TAG)
        VALUES (
                  64,
                  '관리자',
                  NULL,
                  '재능교육연수원 웹사이트 리뉴얼',
                  '1) 소속업체 : (주)재능E아카데미
2) 의뢰업체 : (주)재능E아카데미
3) 목표 : 기존 재능교육 연수원 사이트 리뉴얼
4) 구성원 : 6명
5) 참여도 : 100%
6) 담당업무 : 웹퍼블리싱
'                  ,
                  0,
                  0,
                  '1',
                  '3fbbb66bdbfef670ab96d46cef31e49fa9298894629b9e99b65a070b8b83f169',
                  64,
                  0,
                  1,
                  5,
                  TO_DATE ('04/25/2017 06:56:58', 'MM/DD/YYYY HH24:MI:SS'),
                  1,
                  NULL,
                  '100',
                  '2016-04-08',
                  '2016-06-22',
                  'jSP, CSS, HTML, javascript',
                  'http://www.jeildc.com/',
                  '#재능, #웹퍼블리싱, #재능E아카데이');

INSERT INTO BOARD_PORTFOLIO (BO_IDX,
                             BO_WRITER,
                             BO_MEMBER,
                             BO_SUBJECT,
                             BO_CONTENT,
                             BO_IS_SECRET,
                             BO_IS_NOTICE,
                             BO_FILE,
                             BO_PASS,
                             BO_REF,
                             BO_LEVEL,
                             BO_STEP,
                             BO_HIT,
                             BO_REGDATE,
                             BO_IS_VIEW,
                             BO_IP,
                             BO_1,
                             BO_2,
                             BO_3,
                             BO_4,
                             BO_5,
                             BO_TAG)
        VALUES (
                  65,
                  '관리자',
                  NULL,
                  '(주)시노서울 리뉴얼',
                  '1) 소속업체 : (주)윅슨어소시에이츠 (프리랜서)
2) 의뢰업체 : (주)시노서울
3) 목표 : 웹사이트 리뉴얼 퍼블리싱 , 개발
4) 구성원 : 2명
5) 참여도 : 개발/퍼블리싱 100%
6) 담당업무 : 퍼블리싱 , 개발

그누보드 커스텀으로 백엔드 작업을 하였습니다. 기존 DB 내용이 많아서 CSV 로 디비를 내보낸 뒤 가공하여 작업하였습니다.
반응형으로 작업되었고, Ajax 를 사용하여 관리자단에서 데이터를 입력할 때 편하게 작업할 수 있도록 개발하였습니다.',
                  0,
                  0,
                  '3',
                  '3fbbb66bdbfef670ab96d46cef31e49fa9298894629b9e99b65a070b8b83f169',
                  65,
                  0,
                  1,
                  13,
                  TO_DATE ('04/25/2017 07:03:07', 'MM/DD/YYYY HH24:MI:SS'),
                  1,
                  NULL,
                  '100',
                  '2016-10-08',
                  '2016-10-20',
                  'PHP, HTML, 그누보드, javascript, CSS',
                  'http://sinoseoul.co.kr/',
                  '#시노서울, #웹퍼블리싱, #개발, #반응형');

INSERT INTO BOARD_PORTFOLIO (BO_IDX,
                             BO_WRITER,
                             BO_MEMBER,
                             BO_SUBJECT,
                             BO_CONTENT,
                             BO_IS_SECRET,
                             BO_IS_NOTICE,
                             BO_FILE,
                             BO_PASS,
                             BO_REF,
                             BO_LEVEL,
                             BO_STEP,
                             BO_HIT,
                             BO_REGDATE,
                             BO_IS_VIEW,
                             BO_IP,
                             BO_1,
                             BO_2,
                             BO_3,
                             BO_4,
                             BO_5,
                             BO_TAG)
        VALUES (
                  66,
                  '관리자',
                  NULL,
                  '(주)서울라인 리뉴얼',
                  '1) 소속업체 : (주)윅슨어소시에이츠 (프리랜서)
2) 의뢰업체 : (주)시노서울
3) 목표 : 웹사이트 리뉴얼 퍼블리싱 , 개발
4) 구성원 : 2명
5) 참여도 : 개발/퍼블리싱 100%
6) 담당업무 : 퍼블리싱 , 개발

구글 API 를 사용하여 각 터미널을 표시하는 개발을 중점적으로 작업하였습니다.
반응형으로 제작되었습니다.

'                  ,
                  0,
                  0,
                  '4',
                  '3fbbb66bdbfef670ab96d46cef31e49fa9298894629b9e99b65a070b8b83f169',
                  66,
                  0,
                  1,
                  9,
                  TO_DATE ('04/25/2017 07:08:50', 'MM/DD/YYYY HH24:MI:SS'),
                  1,
                  NULL,
                  '100',
                  '2016-11-03',
                  '2016-11-23',
                  'PHP, HTML, 그누보드, javascript, CSS',
                  'http://seline.co.kr/',
                  '#서울라인, #구글API, #반응형');

INSERT INTO BOARD_PORTFOLIO (BO_IDX,
                             BO_WRITER,
                             BO_MEMBER,
                             BO_SUBJECT,
                             BO_CONTENT,
                             BO_IS_SECRET,
                             BO_IS_NOTICE,
                             BO_FILE,
                             BO_PASS,
                             BO_REF,
                             BO_LEVEL,
                             BO_STEP,
                             BO_HIT,
                             BO_REGDATE,
                             BO_IS_VIEW,
                             BO_IP,
                             BO_1,
                             BO_2,
                             BO_3,
                             BO_4,
                             BO_5,
                             BO_TAG)
        VALUES (
                  67,
                  '관리자',
                  NULL,
                  'KPX케미칼 리뉴얼',
                  '1) 소속업체 : (주)윅슨어소시에이츠 (프리랜서)
2) 의뢰업체 : KPX케미칼
3) 목표 : 웹사이트 리뉴얼 퍼블리싱 , 개발
4) 구성원 : 2명
5) 참여도 : 개발/퍼블리싱 100%
6) 담당업무 : 퍼블리싱 , 개발

영문, 국문 개발로 진행하였습니다. 
회사정보API를 사용하여 주식정보를 보여주는 작업을 하였습니다.
반응형으로 제작되었습니다.',
                  0,
                  0,
                  '4',
                  '3fbbb66bdbfef670ab96d46cef31e49fa9298894629b9e99b65a070b8b83f169',
                  67,
                  0,
                  1,
                  10,
                  TO_DATE ('04/25/2017 07:12:44', 'MM/DD/YYYY HH24:MI:SS'),
                  1,
                  NULL,
                  '100',
                  '2016-12-08',
                  '2016-12-22',
                  'PHP, HTML, 그누보드, javascript, CSS',
                  'http://kpxchemical.com/intro.php',
                  '#KPX, #웹퍼블리싱, #반응형, #주식정보API');

INSERT INTO BOARD_PORTFOLIO (BO_IDX,
                             BO_WRITER,
                             BO_MEMBER,
                             BO_SUBJECT,
                             BO_CONTENT,
                             BO_IS_SECRET,
                             BO_IS_NOTICE,
                             BO_FILE,
                             BO_PASS,
                             BO_REF,
                             BO_LEVEL,
                             BO_STEP,
                             BO_HIT,
                             BO_REGDATE,
                             BO_IS_VIEW,
                             BO_IP,
                             BO_1,
                             BO_2,
                             BO_3,
                             BO_4,
                             BO_5,
                             BO_TAG)
        VALUES (
                  68,
                  '관리자',
                  NULL,
                  '한국콘텐츠진흥원 웹사이트개발',
                  '1) 소속업체 : (주)윅슨어소시에이츠 (프리랜서)
2) 의뢰업체 : 한국콘텐츠진흥원
3) 목표 : 웹사이트 개발
4) 구성원 : 2명
5) 참여도 : 개발/퍼블리싱 100%
6) 담당업무 : 퍼블리싱 , 개발
'                  ,
                  0,
                  0,
                  '4',
                  '3fbbb66bdbfef670ab96d46cef31e49fa9298894629b9e99b65a070b8b83f169',
                  68,
                  0,
                  1,
                  17,
                  TO_DATE ('04/25/2017 08:13:18', 'MM/DD/YYYY HH24:MI:SS'),
                  1,
                  NULL,
                  '100',
                  '2016-12-02',
                  '2016-12-29',
                  'PHP, HTML, 그누보드, javascript, CSS',
                  'http://www.kconbiz.kr/',
                  '#진흥원, #웹, #반응형');

INSERT INTO BOARD_PORTFOLIO (BO_IDX,
                             BO_WRITER,
                             BO_MEMBER,
                             BO_SUBJECT,
                             BO_CONTENT,
                             BO_IS_SECRET,
                             BO_IS_NOTICE,
                             BO_FILE,
                             BO_PASS,
                             BO_REF,
                             BO_LEVEL,
                             BO_STEP,
                             BO_HIT,
                             BO_REGDATE,
                             BO_IS_VIEW,
                             BO_IP,
                             BO_1,
                             BO_2,
                             BO_3,
                             BO_4,
                             BO_5,
                             BO_TAG)
        VALUES (
                  69,
                  '관리자',
                  NULL,
                  '북스크랩 앱 개발',
                  '1) 목표 : 북스크랩 앱 개발
2) 구성원 : 1명
3) 참여도 : 개발 100% / 디자인 100%
4) 담당업무 : 디자인 , 개발

[제작이유]
읽고 싶은 책을 정리 / 기억하기 위해
진도체크
기간을 설정하여 학습동기 부여

2017-03-31 ~ 2017-04-07 : 1차완료
2017-04-08 : 안드로이드마켓등록

구글스토어에 앱 개발완료하였습니다.
https://play.google.com/store/apps/details?id=org.mj.android.bookscrap&hl=ko
'                  ,
                  0,
                  0,
                  '4',
                  '3fbbb66bdbfef670ab96d46cef31e49fa9298894629b9e99b65a070b8b83f169',
                  69,
                  0,
                  1,
                  23,
                  TO_DATE ('04/25/2017 08:27:46', 'MM/DD/YYYY HH24:MI:SS'),
                  1,
                  NULL,
                  '100',
                  '2017-03-31',
                  '2017-04-07',
                  'android, java, json',
                  'https://play.google.com/store/apps/details?id=org.mj.android.bookscrap&hl=ko',
                  '#북스크랩, #앱개발');

INSERT INTO MEMBER (MB_IDX,
                    MB_ID,
                    MB_PASS,
                    MB_NAME,
                    MB_EMAIL,
                    MB_REGDATE,
                    MB_LASTEST,
                    MB_BIRTH,
                    MB_ZIP,
                    MB_ADDR1,
                    MB_ADDR2,
                    MB_MAILING,
                    MB_LEVEL,
                    MB_TEL,
                    MB_HP,
                    MB_SALT)
        VALUES (
                  18,
                  'dreamfly25',
                  '8bbb1c1f64b0919ec6089fd160437c992974734136533a280504bd148c1843cf',
                  '이민지',
                  'leeminji25@naver.com',
                  TO_DATE ('04/17/2017 22:37:32', 'MM/DD/YYYY HH24:MI:SS'),
                  TO_DATE ('04/17/2017 22:37:32', 'MM/DD/YYYY HH24:MI:SS'),
                  NULL,
                  '463-953',
                  '경기 성남시 분당구 판교로 20',
                  '202호',
                  1,
                  2,
                  '01032321112',
                  '01233234212',
                  '1fca74f6e63c5e43');

INSERT INTO MEMBER (MB_IDX,
                    MB_ID,
                    MB_PASS,
                    MB_NAME,
                    MB_EMAIL,
                    MB_REGDATE,
                    MB_LASTEST,
                    MB_BIRTH,
                    MB_ZIP,
                    MB_ADDR1,
                    MB_ADDR2,
                    MB_MAILING,
                    MB_LEVEL,
                    MB_TEL,
                    MB_HP,
                    MB_SALT)
        VALUES (
                  19,
                  'admin',
                  '3fbbb66bdbfef670ab96d46cef31e49fa9298894629b9e99b65a070b8b83f169',
                  '관리자',
                  'leeminji25@naver.com11',
                  TO_DATE ('04/20/2017 00:19:21', 'MM/DD/YYYY HH24:MI:SS'),
                  TO_DATE ('05/25/2017 13:18:06', 'MM/DD/YYYY HH24:MI:SS'),
                  NULL,
                  '135-200',
                  '서울 강남구 밤고개로 120',
                  '12121',
                  0,
                  10,
                  '023341240',
                  '01030501240',
                  'a22a31480122be36');

COMMIT;